<?php

/**
 * BaseMappingPair
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $mapping_id
 * @property string $a
 * @property string $b
 * @property Mapping $Mapping
 * 
 * @method integer     getId()         Returns the current record's "id" value
 * @method integer     getMappingId()  Returns the current record's "mapping_id" value
 * @method string      getA()          Returns the current record's "a" value
 * @method string      getB()          Returns the current record's "b" value
 * @method Mapping     getMapping()    Returns the current record's "Mapping" value
 * @method MappingPair setId()         Sets the current record's "id" value
 * @method MappingPair setMappingId()  Sets the current record's "mapping_id" value
 * @method MappingPair setA()          Sets the current record's "a" value
 * @method MappingPair setB()          Sets the current record's "b" value
 * @method MappingPair setMapping()    Sets the current record's "Mapping" value
 * 
 * @package    policat
 * @subpackage model
 * @author     developer-docker
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMappingPair extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mapping_pair');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('mapping_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('a', 'string', 80, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 80,
             ));
        $this->hasColumn('b', 'string', 80, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 80,
             ));


        $this->index('mp_a_idx', array(
             'fields' => 
             array(
              0 => 'mapping_id',
              1 => 'a',
             ),
             ));
        $this->index('mp_ab_idx', array(
             'fields' => 
             array(
              0 => 'mapping_id',
              1 => 'a',
              2 => 'b',
             ),
             'type' => 'unique',
             ));
        $this->option('form', false);
        $this->option('filter', false);
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Mapping', array(
             'local' => 'mapping_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $cachetaggable0 = new Doctrine_Template_Cachetaggable();
        $this->actAs($cachetaggable0);
    }
}