<?php

/**
 * BaseTargetListRights
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int               $mailing_list_id                 Type: integer(4), primary key
 * @property int               $user_id                         Type: integer(4), primary key
 * @property int               $active                          Type: integer(1)
 * @property MailingList       $MailingList                     
 * @property sfGuardUser       $User                            
 *  
 * @method int                 getMailingListId()               Type: integer(4), primary key
 * @method int                 getUserId()                      Type: integer(4), primary key
 * @method int                 getActive()                      Type: integer(1)
 * @method MailingList         getMailingList()                 
 * @method sfGuardUser         getUser()                        
 *  
 * @method TargetListRights    setMailingListId(int $val)       Type: integer(4), primary key
 * @method TargetListRights    setUserId(int $val)              Type: integer(4), primary key
 * @method TargetListRights    setActive(int $val)              Type: integer(1)
 * @method TargetListRights    setMailingList(MailingList $val) 
 * @method TargetListRights    setUser(sfGuardUser $val)        
 *  
 * @package    policat
 * @subpackage model
 * @author     Martin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTargetListRights extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('target_list_rights');
        $this->hasColumn('mailing_list_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('active', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 1,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MailingList', array(
             'local' => 'mailing_list_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}