<?php

/**
 * BaseMailingList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                                     $id                                           Type: integer(4), primary key
 * @property int                                     $status                                       Type: integer(4), default "1"
 * @property int                                     $campaign_id                                  Type: integer(4)
 * @property string                                  $name                                         Type: string
 * @property Campaign                                $Campaign                                     
 * @property Doctrine_Collection|Petition[]          $Petition                                     
 * @property Doctrine_Collection|MailingListMeta[]   $MailingListMeta                              
 * @property Doctrine_Collection|Contact[]           $Contact                                      
 * @property Doctrine_Collection|TargetListRights[]  $TargetListRights                             
 * @property Doctrine_Collection|Ticket[]            $Tickets                                      
 *  
 * @method int                                       getId()                                       Type: integer(4), primary key
 * @method int                                       getStatus()                                   Type: integer(4), default "1"
 * @method int                                       getCampaignId()                               Type: integer(4)
 * @method string                                    getName()                                     Type: string
 * @method Campaign                                  getCampaign()                                 
 * @method Doctrine_Collection|Petition[]            getPetition()                                 
 * @method Doctrine_Collection|MailingListMeta[]     getMailingListMeta()                          
 * @method Doctrine_Collection|Contact[]             getContact()                                  
 * @method Doctrine_Collection|TargetListRights[]    getTargetListRights()                         
 * @method Doctrine_Collection|Ticket[]              getTickets()                                  
 *  
 * @method MailingList                               setId(int $val)                               Type: integer(4), primary key
 * @method MailingList                               setStatus(int $val)                           Type: integer(4), default "1"
 * @method MailingList                               setCampaignId(int $val)                       Type: integer(4)
 * @method MailingList                               setName(string $val)                          Type: string
 * @method MailingList                               setCampaign(Campaign $val)                    
 * @method MailingList                               setPetition(Doctrine_Collection $val)         
 * @method MailingList                               setMailingListMeta(Doctrine_Collection $val)  
 * @method MailingList                               setContact(Doctrine_Collection $val)          
 * @method MailingList                               setTargetListRights(Doctrine_Collection $val) 
 * @method MailingList                               setTickets(Doctrine_Collection $val)          
 *  
 * @package    policat
 * @subpackage model
 * @author     Martin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMailingList extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mailing_list');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('status', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             'length' => 4,
             ));
        $this->hasColumn('campaign_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));

        $this->option('symfony', array(
             'form' => true,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Campaign', array(
             'local' => 'campaign_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Petition', array(
             'local' => 'id',
             'foreign' => 'mailing_list_id'));

        $this->hasMany('MailingListMeta', array(
             'local' => 'id',
             'foreign' => 'mailing_list_id'));

        $this->hasMany('Contact', array(
             'local' => 'id',
             'foreign' => 'mailing_list_id'));

        $this->hasMany('TargetListRights', array(
             'local' => 'id',
             'foreign' => 'mailing_list_id'));

        $this->hasMany('Ticket as Tickets', array(
             'local' => 'id',
             'foreign' => 'target_list_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $cachetaggable0 = new Doctrine_Template_Cachetaggable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($cachetaggable0);
    }
}