<?php

/**
 * BaseMapping
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                                $id                                Type: integer(4), primary key
 * @property string                             $name                              Type: string(120), unique
 * @property Doctrine_Collection|MappingPair[]  $Pairs                             
 *  
 * @method int                                  getId()                            Type: integer(4), primary key
 * @method string                               getName()                          Type: string(120), unique
 * @method Doctrine_Collection|MappingPair[]    getPairs()                         
 *  
 * @method Mapping                              setId(int $val)                    Type: integer(4), primary key
 * @method Mapping                              setName(string $val)               Type: string(120), unique
 * @method Mapping                              setPairs(Doctrine_Collection $val) 
 *  
 * @package    policat
 * @subpackage model
 * @author     Martin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMapping extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mapping');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 120,
             ));

        $this->option('symfony', array(
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('MappingPair as Pairs', array(
             'local' => 'id',
             'foreign' => 'mapping_id'));

        $cachetaggable0 = new Doctrine_Template_Cachetaggable();
        $this->actAs($cachetaggable0);
    }
}