<?php

/**
 * BaseQuota
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                                    $id                                                   Type: integer(4), primary key
 * @property int                                    $status                                               Type: integer(4), default "1"
 * @property string                                 $name                                                 Type: string(120)
 * @property float                                  $price                                                Type: decimal(10)
 * @property int                                    $days                                                 Type: integer(4)
 * @property int                                    $emails                                               Type: integer(4)
 * @property int                                    $subscription                                         Type: integer(1)
 * @property int                                    $renew_offerred                                       Type: integer(1)
 * @property int                                    $user_id                                              Type: integer(4)
 * @property int                                    $campaign_id                                          Type: integer(4)
 * @property string                                 $start_at                                             Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @property string                                 $end_at                                               Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @property string                                 $paid_at                                              Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @property int                                    $emails_remaining                                     Type: integer(4)
 * @property int                                    $order_id                                             Type: integer(4)
 * @property int                                    $upgrade_of_id                                        Type: integer(4)
 * @property int                                    $product_id                                           Type: integer(4)
 * @property sfGuardUser                            $User                                                 
 * @property Campaign                               $Campaign                                             
 * @property Product                                $Product                                              
 * @property Order                                  $Order                                                
 * @property Quota                                  $UpgradeOf                                            
 * @property Campaign                               $activeCampaign                                       
 * @property Doctrine_Collection|PetitionSigning[]  $PetitionSigning                                      
 * @property Doctrine_Collection|PetitionSigning[]  $PetitionSigningThankYous                             
 * @property Quota                                  $UpgradedBy                                           
 *  
 * @method int                                      getId()                                               Type: integer(4), primary key
 * @method int                                      getStatus()                                           Type: integer(4), default "1"
 * @method string                                   getName()                                             Type: string(120)
 * @method float                                    getPrice()                                            Type: decimal(10)
 * @method int                                      getDays()                                             Type: integer(4)
 * @method int                                      getEmails()                                           Type: integer(4)
 * @method int                                      getSubscription()                                     Type: integer(1)
 * @method int                                      getRenewOfferred()                                    Type: integer(1)
 * @method int                                      getUserId()                                           Type: integer(4)
 * @method int                                      getCampaignId()                                       Type: integer(4)
 * @method string                                   getStartAt()                                          Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @method string                                   getEndAt()                                            Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @method string                                   getPaidAt()                                           Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @method int                                      getEmailsRemaining()                                  Type: integer(4)
 * @method int                                      getOrderId()                                          Type: integer(4)
 * @method int                                      getUpgradeOfId()                                      Type: integer(4)
 * @method int                                      getProductId()                                        Type: integer(4)
 * @method sfGuardUser                              getUser()                                             
 * @method Campaign                                 getCampaign()                                         
 * @method Product                                  getProduct()                                          
 * @method Order                                    getOrder()                                            
 * @method Quota                                    getUpgradeOf()                                        
 * @method Campaign                                 getActiveCampaign()                                   
 * @method Doctrine_Collection|PetitionSigning[]    getPetitionSigning()                                  
 * @method Doctrine_Collection|PetitionSigning[]    getPetitionSigningThankYous()                         
 * @method Quota                                    getUpgradedBy()                                       
 *  
 * @method Quota                                    setId(int $val)                                       Type: integer(4), primary key
 * @method Quota                                    setStatus(int $val)                                   Type: integer(4), default "1"
 * @method Quota                                    setName(string $val)                                  Type: string(120)
 * @method Quota                                    setPrice(float $val)                                  Type: decimal(10)
 * @method Quota                                    setDays(int $val)                                     Type: integer(4)
 * @method Quota                                    setEmails(int $val)                                   Type: integer(4)
 * @method Quota                                    setSubscription(int $val)                             Type: integer(1)
 * @method Quota                                    setRenewOfferred(int $val)                            Type: integer(1)
 * @method Quota                                    setUserId(int $val)                                   Type: integer(4)
 * @method Quota                                    setCampaignId(int $val)                               Type: integer(4)
 * @method Quota                                    setStartAt(string $val)                               Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @method Quota                                    setEndAt(string $val)                                 Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @method Quota                                    setPaidAt(string $val)                                Type: date, Date in ISO-8601 format (YYYY-MM-DD)
 * @method Quota                                    setEmailsRemaining(int $val)                          Type: integer(4)
 * @method Quota                                    setOrderId(int $val)                                  Type: integer(4)
 * @method Quota                                    setUpgradeOfId(int $val)                              Type: integer(4)
 * @method Quota                                    setProductId(int $val)                                Type: integer(4)
 * @method Quota                                    setUser(sfGuardUser $val)                             
 * @method Quota                                    setCampaign(Campaign $val)                            
 * @method Quota                                    setProduct(Product $val)                              
 * @method Quota                                    setOrder(Order $val)                                  
 * @method Quota                                    setUpgradeOf(Quota $val)                              
 * @method Quota                                    setActiveCampaign(Campaign $val)                      
 * @method Quota                                    setPetitionSigning(Doctrine_Collection $val)          
 * @method Quota                                    setPetitionSigningThankYous(Doctrine_Collection $val) 
 * @method Quota                                    setUpgradedBy(Quota $val)                             
 *  
 * @package    policat
 * @subpackage model
 * @author     Martin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuota extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('quota');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('status', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('price', 'decimal', 10, array(
             'type' => 'decimal',
             'notnull' => true,
             'scale' => 2,
             'length' => 10,
             ));
        $this->hasColumn('days', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('emails', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('subscription', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('renew_offerred', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('campaign_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('start_at', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('end_at', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('paid_at', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('emails_remaining', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('order_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('upgrade_of_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('product_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Campaign', array(
             'local' => 'campaign_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Product', array(
             'local' => 'product_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Order', array(
             'local' => 'order_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Quota as UpgradeOf', array(
             'local' => 'upgrade_of_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Campaign as activeCampaign', array(
             'local' => 'id',
             'foreign' => 'quota_id'));

        $this->hasMany('PetitionSigning', array(
             'local' => 'id',
             'foreign' => 'quota_id'));

        $this->hasMany('PetitionSigning as PetitionSigningThankYous', array(
             'local' => 'id',
             'foreign' => 'quota_thank_you_id'));

        $this->hasOne('Quota as UpgradedBy', array(
             'local' => 'id',
             'foreign' => 'upgrade_of_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}