<?php
/*
 * Copyright (c) 2015, webvariants GmbH & Co. KG, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

/**
 * BasePrivacyPolicy
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property string $language_id
 * @property clob $body
 * @property Language $Language
 *
 * @method string        getLanguageId()  Returns the current record's "language_id" value
 * @method clob          getBody()        Returns the current record's "body" value
 * @method Language      getLanguage()    Returns the current record's "Language" value
 * @method PrivacyPolicy setLanguageId()  Sets the current record's "language_id" value
 * @method PrivacyPolicy setBody()        Sets the current record's "body" value
 * @method PrivacyPolicy setLanguage()    Sets the current record's "Language" value
 *
 * @package    policat
 * @subpackage model
 * @author     Martin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePrivacyPolicy extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('privacy_policy');
        $this->hasColumn('language_id', 'string', 5, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('body', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));

        $this->option('symfony', array(
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Language', array(
             'local' => 'language_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}
