<?php

/**
 * BasePetitionRights
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int             $petition_id               Type: integer(4), primary key
 * @property int             $user_id                   Type: integer(4), primary key
 * @property int             $active                    Type: integer(1)
 * @property int             $member                    Type: integer(1)
 * @property int             $admin                     Type: integer(1)
 * @property Petition        $Petition                  
 * @property sfGuardUser     $User                      
 *  
 * @method int               getPetitionId()            Type: integer(4), primary key
 * @method int               getUserId()                Type: integer(4), primary key
 * @method int               getActive()                Type: integer(1)
 * @method int               getMember()                Type: integer(1)
 * @method int               getAdmin()                 Type: integer(1)
 * @method Petition          getPetition()              
 * @method sfGuardUser       getUser()                  
 *  
 * @method PetitionRights    setPetitionId(int $val)    Type: integer(4), primary key
 * @method PetitionRights    setUserId(int $val)        Type: integer(4), primary key
 * @method PetitionRights    setActive(int $val)        Type: integer(1)
 * @method PetitionRights    setMember(int $val)        Type: integer(1)
 * @method PetitionRights    setAdmin(int $val)         Type: integer(1)
 * @method PetitionRights    setPetition(Petition $val) 
 * @method PetitionRights    setUser(sfGuardUser $val)  
 *  
 * @package    policat
 * @subpackage model
 * @author     Martin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePetitionRights extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('petition_rights');
        $this->hasColumn('petition_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('active', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('member', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('admin', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 1,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Petition', array(
             'local' => 'petition_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}