<?php

/**
 * BasePetitionSigning
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                                           $id                                                 Type: integer(8), primary key
 * @property int                                           $petition_id                                        Type: integer(4)
 * @property int                                           $campaign_id                                        Type: integer(4)
 * @property int                                           $petition_text_id                                   Type: integer(4)
 * @property string                                        $language_id                                        Type: string(5)
 * @property string                                        $fields                                             Type: clob
 * @property int                                           $status                                             Type: integer(4), default "1"
 * @property int                                           $petition_status                                    Type: integer(4), default "1"
 * @property int                                           $petition_enabled                                   Type: integer(1), default "1"
 * @property int                                           $verified                                           Type: integer(4)
 * @property string                                        $email                                              Type: string(80)
 * @property string                                        $country                                            Type: string(5)
 * @property int                                           $validation_kind                                    Type: integer(1)
 * @property string                                        $validation_data                                    Type: string(16)
 * @property string                                        $delete_code                                        Type: string(16)
 * @property int                                           $widget_id                                          Type: integer(4)
 * @property int                                           $wave_sent                                          Type: integer(2)
 * @property int                                           $wave_pending                                       Type: integer(2)
 * @property int                                           $wave_cron                                          Type: integer(1)
 * @property int                                           $subscribe                                          Type: integer(1)
 * @property string                                        $email_hash                                         Type: string(80)
 * @property string                                        $mailed_at                                          Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @property string                                        $fullname                                           Type: string(120)
 * @property string                                        $title                                              Type: string(10)
 * @property string                                        $firstname                                          Type: string(100)
 * @property string                                        $lastname                                           Type: string(100)
 * @property string                                        $address                                            Type: string(200)
 * @property string                                        $city                                               Type: string(100)
 * @property string                                        $post_code                                          Type: string(50)
 * @property string                                        $comment                                            Type: clob
 * @property string                                        $extra1                                             Type: string(100)
 * @property string                                        $extra2                                             Type: string(100)
 * @property string                                        $extra3                                             Type: string(100)
 * @property int                                           $privacy                                            Type: integer(1)
 * @property string                                        $email_subject                                      Type: string(250)
 * @property string                                        $email_body                                         Type: clob
 * @property string                                        $ref                                                Type: string(250)
 * @property int                                           $quota_id                                           Type: integer(4)
 * @property int                                           $quota_emails                                       Type: integer(2)
 * @property int                                           $thank_sent                                         Type: integer(1)
 * @property int                                           $quota_thank_you_id                                 Type: integer(4)
 * @property int                                           $bounce                                             Type: integer(1)
 * @property string                                        $bounce_at                                          Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @property int                                           $bounce_blocked                                     Type: integer(1)
 * @property int                                           $bounce_hard                                        Type: integer(1)
 * @property string                                        $bounce_related_to                                  Type: string(20)
 * @property string                                        $bounce_error                                       Type: string(20)
 * @property int                                           $download_subscriber_id                             Type: integer(4)
 * @property int                                           $download_data_id                                   Type: integer(4)
 * @property Petition                                      $Petition                                           
 * @property Campaign                                      $Campaign                                           
 * @property PetitionText                                  $PetitionText                                       
 * @property Language                                      $Language                                           
 * @property Widget                                        $Widget                                             
 * @property Doctrine_Collection|Contact[]                 $Contact                                            
 * @property Quota                                         $Quota                                              
 * @property Quota                                         $QuotaThankYou                                      
 * @property Download                                      $DownloadSubscriber                                 
 * @property Download                                      $DownloadData                                       
 * @property Doctrine_Collection|PetitionSigningSearch[]   $Search                                             
 * @property Doctrine_Collection|PetitionSigningContact[]  $PetitionSigningContact                             
 * @property Doctrine_Collection|PetitionSigningWave[]     $PetitionSigningWave                                
 * @property Doctrine_Collection|DigestEmail[]             $DigestEmails                                       
 *  
 * @method int                                             getId()                                             Type: integer(8), primary key
 * @method int                                             getPetitionId()                                     Type: integer(4)
 * @method int                                             getCampaignId()                                     Type: integer(4)
 * @method int                                             getPetitionTextId()                                 Type: integer(4)
 * @method string                                          getLanguageId()                                     Type: string(5)
 * @method string                                          getFields()                                         Type: clob
 * @method int                                             getStatus()                                         Type: integer(4), default "1"
 * @method int                                             getPetitionStatus()                                 Type: integer(4), default "1"
 * @method int                                             getPetitionEnabled()                                Type: integer(1), default "1"
 * @method int                                             getVerified()                                       Type: integer(4)
 * @method string                                          getEmail()                                          Type: string(80)
 * @method string                                          getCountry()                                        Type: string(5)
 * @method int                                             getValidationKind()                                 Type: integer(1)
 * @method string                                          getValidationData()                                 Type: string(16)
 * @method string                                          getDeleteCode()                                     Type: string(16)
 * @method int                                             getWidgetId()                                       Type: integer(4)
 * @method int                                             getWaveSent()                                       Type: integer(2)
 * @method int                                             getWavePending()                                    Type: integer(2)
 * @method int                                             getWaveCron()                                       Type: integer(1)
 * @method int                                             getSubscribe()                                      Type: integer(1)
 * @method string                                          getEmailHash()                                      Type: string(80)
 * @method string                                          getMailedAt()                                       Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method string                                          getFullname()                                       Type: string(120)
 * @method string                                          getTitle()                                          Type: string(10)
 * @method string                                          getFirstname()                                      Type: string(100)
 * @method string                                          getLastname()                                       Type: string(100)
 * @method string                                          getAddress()                                        Type: string(200)
 * @method string                                          getCity()                                           Type: string(100)
 * @method string                                          getPostCode()                                       Type: string(50)
 * @method string                                          getComment()                                        Type: clob
 * @method string                                          getExtra1()                                         Type: string(100)
 * @method string                                          getExtra2()                                         Type: string(100)
 * @method string                                          getExtra3()                                         Type: string(100)
 * @method int                                             getPrivacy()                                        Type: integer(1)
 * @method string                                          getEmailSubject()                                   Type: string(250)
 * @method string                                          getEmailBody()                                      Type: clob
 * @method string                                          getRef()                                            Type: string(250)
 * @method int                                             getQuotaId()                                        Type: integer(4)
 * @method int                                             getQuotaEmails()                                    Type: integer(2)
 * @method int                                             getThankSent()                                      Type: integer(1)
 * @method int                                             getQuotaThankYouId()                                Type: integer(4)
 * @method int                                             getBounce()                                         Type: integer(1)
 * @method string                                          getBounceAt()                                       Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method int                                             getBounceBlocked()                                  Type: integer(1)
 * @method int                                             getBounceHard()                                     Type: integer(1)
 * @method string                                          getBounceRelatedTo()                                Type: string(20)
 * @method string                                          getBounceError()                                    Type: string(20)
 * @method int                                             getDownloadSubscriberId()                           Type: integer(4)
 * @method int                                             getDownloadDataId()                                 Type: integer(4)
 * @method Petition                                        getPetition()                                       
 * @method Campaign                                        getCampaign()                                       
 * @method PetitionText                                    getPetitionText()                                   
 * @method Language                                        getLanguage()                                       
 * @method Widget                                          getWidget()                                         
 * @method Doctrine_Collection|Contact[]                   getContact()                                        
 * @method Quota                                           getQuota()                                          
 * @method Quota                                           getQuotaThankYou()                                  
 * @method Download                                        getDownloadSubscriber()                             
 * @method Download                                        getDownloadData()                                   
 * @method Doctrine_Collection|PetitionSigningSearch[]     getSearch()                                         
 * @method Doctrine_Collection|PetitionSigningContact[]    getPetitionSigningContact()                         
 * @method Doctrine_Collection|PetitionSigningWave[]       getPetitionSigningWave()                            
 * @method Doctrine_Collection|DigestEmail[]               getDigestEmails()                                   
 *  
 * @method PetitionSigning                                 setId(int $val)                                     Type: integer(8), primary key
 * @method PetitionSigning                                 setPetitionId(int $val)                             Type: integer(4)
 * @method PetitionSigning                                 setCampaignId(int $val)                             Type: integer(4)
 * @method PetitionSigning                                 setPetitionTextId(int $val)                         Type: integer(4)
 * @method PetitionSigning                                 setLanguageId(string $val)                          Type: string(5)
 * @method PetitionSigning                                 setFields(string $val)                              Type: clob
 * @method PetitionSigning                                 setStatus(int $val)                                 Type: integer(4), default "1"
 * @method PetitionSigning                                 setPetitionStatus(int $val)                         Type: integer(4), default "1"
 * @method PetitionSigning                                 setPetitionEnabled(int $val)                        Type: integer(1), default "1"
 * @method PetitionSigning                                 setVerified(int $val)                               Type: integer(4)
 * @method PetitionSigning                                 setEmail(string $val)                               Type: string(80)
 * @method PetitionSigning                                 setCountry(string $val)                             Type: string(5)
 * @method PetitionSigning                                 setValidationKind(int $val)                         Type: integer(1)
 * @method PetitionSigning                                 setValidationData(string $val)                      Type: string(16)
 * @method PetitionSigning                                 setDeleteCode(string $val)                          Type: string(16)
 * @method PetitionSigning                                 setWidgetId(int $val)                               Type: integer(4)
 * @method PetitionSigning                                 setWaveSent(int $val)                               Type: integer(2)
 * @method PetitionSigning                                 setWavePending(int $val)                            Type: integer(2)
 * @method PetitionSigning                                 setWaveCron(int $val)                               Type: integer(1)
 * @method PetitionSigning                                 setSubscribe(int $val)                              Type: integer(1)
 * @method PetitionSigning                                 setEmailHash(string $val)                           Type: string(80)
 * @method PetitionSigning                                 setMailedAt(string $val)                            Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method PetitionSigning                                 setFullname(string $val)                            Type: string(120)
 * @method PetitionSigning                                 setTitle(string $val)                               Type: string(10)
 * @method PetitionSigning                                 setFirstname(string $val)                           Type: string(100)
 * @method PetitionSigning                                 setLastname(string $val)                            Type: string(100)
 * @method PetitionSigning                                 setAddress(string $val)                             Type: string(200)
 * @method PetitionSigning                                 setCity(string $val)                                Type: string(100)
 * @method PetitionSigning                                 setPostCode(string $val)                            Type: string(50)
 * @method PetitionSigning                                 setComment(string $val)                             Type: clob
 * @method PetitionSigning                                 setExtra1(string $val)                              Type: string(100)
 * @method PetitionSigning                                 setExtra2(string $val)                              Type: string(100)
 * @method PetitionSigning                                 setExtra3(string $val)                              Type: string(100)
 * @method PetitionSigning                                 setPrivacy(int $val)                                Type: integer(1)
 * @method PetitionSigning                                 setEmailSubject(string $val)                        Type: string(250)
 * @method PetitionSigning                                 setEmailBody(string $val)                           Type: clob
 * @method PetitionSigning                                 setRef(string $val)                                 Type: string(250)
 * @method PetitionSigning                                 setQuotaId(int $val)                                Type: integer(4)
 * @method PetitionSigning                                 setQuotaEmails(int $val)                            Type: integer(2)
 * @method PetitionSigning                                 setThankSent(int $val)                              Type: integer(1)
 * @method PetitionSigning                                 setQuotaThankYouId(int $val)                        Type: integer(4)
 * @method PetitionSigning                                 setBounce(int $val)                                 Type: integer(1)
 * @method PetitionSigning                                 setBounceAt(string $val)                            Type: timestamp, Timestamp in ISO-8601 format (YYYY-MM-DD HH:MI:SS)
 * @method PetitionSigning                                 setBounceBlocked(int $val)                          Type: integer(1)
 * @method PetitionSigning                                 setBounceHard(int $val)                             Type: integer(1)
 * @method PetitionSigning                                 setBounceRelatedTo(string $val)                     Type: string(20)
 * @method PetitionSigning                                 setBounceError(string $val)                         Type: string(20)
 * @method PetitionSigning                                 setDownloadSubscriberId(int $val)                   Type: integer(4)
 * @method PetitionSigning                                 setDownloadDataId(int $val)                         Type: integer(4)
 * @method PetitionSigning                                 setPetition(Petition $val)                          
 * @method PetitionSigning                                 setCampaign(Campaign $val)                          
 * @method PetitionSigning                                 setPetitionText(PetitionText $val)                  
 * @method PetitionSigning                                 setLanguage(Language $val)                          
 * @method PetitionSigning                                 setWidget(Widget $val)                              
 * @method PetitionSigning                                 setContact(Doctrine_Collection $val)                
 * @method PetitionSigning                                 setQuota(Quota $val)                                
 * @method PetitionSigning                                 setQuotaThankYou(Quota $val)                        
 * @method PetitionSigning                                 setDownloadSubscriber(Download $val)                
 * @method PetitionSigning                                 setDownloadData(Download $val)                      
 * @method PetitionSigning                                 setSearch(Doctrine_Collection $val)                 
 * @method PetitionSigning                                 setPetitionSigningContact(Doctrine_Collection $val) 
 * @method PetitionSigning                                 setPetitionSigningWave(Doctrine_Collection $val)    
 * @method PetitionSigning                                 setDigestEmails(Doctrine_Collection $val)           
 *  
 * @package    policat
 * @subpackage model
 * @author     Martin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePetitionSigning extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('petition_signing');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('petition_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('campaign_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('petition_text_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('language_id', 'string', 5, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 5,
             ));
        $this->hasColumn('fields', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('status', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             'length' => 4,
             ));
        $this->hasColumn('petition_status', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             'length' => 4,
             ));
        $this->hasColumn('petition_enabled', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             'length' => 1,
             ));
        $this->hasColumn('verified', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('email', 'string', 80, array(
             'type' => 'string',
             'length' => 80,
             ));
        $this->hasColumn('country', 'string', 5, array(
             'type' => 'string',
             'length' => 5,
             ));
        $this->hasColumn('validation_kind', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('validation_data', 'string', 16, array(
             'type' => 'string',
             'length' => 16,
             ));
        $this->hasColumn('delete_code', 'string', 16, array(
             'type' => 'string',
             'length' => 16,
             ));
        $this->hasColumn('widget_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('wave_sent', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 2,
             ));
        $this->hasColumn('wave_pending', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 2,
             ));
        $this->hasColumn('wave_cron', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('subscribe', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('email_hash', 'string', 80, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 80,
             ));
        $this->hasColumn('mailed_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => false,
             ));
        $this->hasColumn('fullname', 'string', 120, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 120,
             ));
        $this->hasColumn('title', 'string', 10, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 10,
             ));
        $this->hasColumn('firstname', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 100,
             ));
        $this->hasColumn('lastname', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 100,
             ));
        $this->hasColumn('address', 'string', 200, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 200,
             ));
        $this->hasColumn('city', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 100,
             ));
        $this->hasColumn('post_code', 'string', 50, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 50,
             ));
        $this->hasColumn('comment', 'clob', null, array(
             'type' => 'clob',
             'notnull' => false,
             ));
        $this->hasColumn('extra1', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 100,
             ));
        $this->hasColumn('extra2', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 100,
             ));
        $this->hasColumn('extra3', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 100,
             ));
        $this->hasColumn('privacy', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 1,
             ));
        $this->hasColumn('email_subject', 'string', 250, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 250,
             ));
        $this->hasColumn('email_body', 'clob', null, array(
             'type' => 'clob',
             'notnull' => false,
             ));
        $this->hasColumn('ref', 'string', 250, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 250,
             ));
        $this->hasColumn('quota_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('quota_emails', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 2,
             ));
        $this->hasColumn('thank_sent', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('quota_thank_you_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('bounce', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('bounce_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => false,
             ));
        $this->hasColumn('bounce_blocked', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('bounce_hard', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('bounce_related_to', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('bounce_error', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('download_subscriber_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('download_data_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));


        $this->index('signing_petition_count_index2', array(
             'fields' => 
             array(
              0 => 'petition_id',
              1 => 'status',
              2 => 'created_at',
             ),
             ));
        $this->index('signing_petition_count_index3', array(
             'fields' => 
             array(
              0 => 'petition_id',
              1 => 'status',
              2 => 'country',
              3 => 'created_at',
             ),
             ));
        $this->index('signing_widget_count_index2', array(
             'fields' => 
             array(
              0 => 'widget_id',
              1 => 'status',
              2 => 'country',
              3 => 'created_at',
             ),
             ));
        $this->index('signing_widget_count_index3', array(
             'fields' => 
             array(
              0 => 'widget_id',
              1 => 'status',
              2 => 'created_at',
             ),
             ));
        $this->index('signing_widget_count_index4', array(
             'fields' => 
             array(
              0 => 'widget_id',
              1 => 'status',
              2 => 'subscribe',
              3 => 'created_at',
             ),
             ));
        $this->index('signing_wave_sent_index', array(
             'fields' => 
             array(
              0 => 'wave_sent',
             ),
             ));
        $this->index('signing_wave_pending_index', array(
             'fields' => 
             array(
              0 => 'wave_pending',
             ),
             ));
        $this->index('signing_wave_cron_index', array(
             'fields' => 
             array(
              0 => 'wave_cron',
             ),
             ));
        $this->index('signing_subsrcibe', array(
             'fields' => 
             array(
              0 => 'subscribe',
             ),
             ));
        $this->index('signing_country', array(
             'fields' => 
             array(
              0 => 'country',
             ),
             ));
        $this->index('signing_pending_index2', array(
             'fields' => 
             array(
              0 => 'status',
              1 => 'created_at',
              2 => 'id',
             ),
             ));
        $this->index('signing_pending_index3', array(
             'fields' => 
             array(
              0 => 'status',
              1 => 'mailed_at',
              2 => 'updated_at',
              3 => 'id',
             ),
             ));
        $this->index('signing_email_duplicate', array(
             'fields' => 
             array(
              0 => 'petition_id',
              1 => 'email',
             ),
             ));
        $this->index('signing_last_signers', array(
             'fields' => 
             array(
              0 => 'petition_id',
              1 => 'status',
              2 => 'updated_at',
             ),
             ));
        $this->index('signing_list_country', array(
             'fields' => 
             array(
              0 => 'petition_id',
              1 => 'status',
              2 => 'country',
              3 => 'city',
              4 => 'id',
             ),
             ));
        $this->index('signing_bounce', array(
             'fields' => 
             array(
              0 => 'petition_id',
              1 => 'bounce',
              2 => 'verified',
              3 => 'bounce_at',
             ),
             ));
        $this->index('signing_inc_dl_sub', array(
             'fields' => 
             array(
              0 => 'petition_id',
              1 => 'download_subscriber_id',
              2 => 'status',
              3 => 'subscribe',
              4 => 'id',
             ),
             ));
        $this->index('signing_inc_dl_data', array(
             'fields' => 
             array(
              0 => 'petition_id',
              1 => 'download_data_id',
              2 => 'status',
              3 => 'id',
             ),
             ));
        $this->index('signing_language1', array(
             'fields' => 
             array(
              0 => 'petition_id',
              1 => 'status',
              2 => 'language_id',
             ),
             ));
        $this->index('signing_language2', array(
             'fields' => 
             array(
              0 => 'widget_id',
              1 => 'status',
              2 => 'language_id',
             ),
             ));
        $this->index('signing_language3', array(
             'fields' => 
             array(
              0 => 'campaign_id',
              1 => 'petition_enabled',
              2 => 'status',
              3 => 'language_id',
              4 => 'id',
             ),
             ));
        $this->index('signing_list_campaign', array(
             'fields' => 
             array(
              0 => 'campaign_id',
              1 => 'petition_enabled',
              2 => 'status',
              3 => 'id',
             ),
             ));
        $this->index('signing_campaign_country', array(
             'fields' => 
             array(
              0 => 'campaign_id',
              1 => 'petition_enabled',
              2 => 'status',
              3 => 'country',
             ),
             ));
        $this->option('options', NULL);
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Petition', array(
             'local' => 'petition_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Campaign', array(
             'local' => 'campaign_id',
             'foreign' => 'id'));

        $this->hasOne('PetitionText', array(
             'local' => 'petition_text_id',
             'foreign' => 'id'));

        $this->hasOne('Language', array(
             'local' => 'language_id',
             'foreign' => 'id'));

        $this->hasOne('Widget', array(
             'local' => 'widget_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('Contact', array(
             'refClass' => 'PetitionSigningContact',
             'local' => 'petition_signing_id',
             'foreign' => 'contact_id'));

        $this->hasOne('Quota', array(
             'local' => 'quota_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Quota as QuotaThankYou', array(
             'local' => 'quota_thank_you_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Download as DownloadSubscriber', array(
             'local' => 'download_subscriber_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Download as DownloadData', array(
             'local' => 'download_data_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('PetitionSigningSearch as Search', array(
             'local' => 'id',
             'foreign' => 'id'));

        $this->hasMany('PetitionSigningContact', array(
             'local' => 'id',
             'foreign' => 'petition_signing_id'));

        $this->hasMany('PetitionSigningWave', array(
             'local' => 'id',
             'foreign' => 'petition_signing_id'));

        $this->hasMany('DigestEmail as DigestEmails', array(
             'local' => 'id',
             'foreign' => 'petition_signing_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}