<?php

/**
 * BaseMailingListMetaChoice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                                $id                                      Type: integer(4), primary key
 * @property int                                $mailing_list_meta_id                    Type: integer(4)
 * @property string                             $choice                                  Type: string(120)
 * @property MailingListMeta                    $MailingListMeta                         
 * @property Doctrine_Collection|ContactMeta[]  $ContactMeta                             
 *  
 * @method int                                  getId()                                  Type: integer(4), primary key
 * @method int                                  getMailingListMetaId()                   Type: integer(4)
 * @method string                               getChoice()                              Type: string(120)
 * @method MailingListMeta                      getMailingListMeta()                     
 * @method Doctrine_Collection|ContactMeta[]    getContactMeta()                         
 *  
 * @method MailingListMetaChoice                setId(int $val)                          Type: integer(4), primary key
 * @method MailingListMetaChoice                setMailingListMetaId(int $val)           Type: integer(4)
 * @method MailingListMetaChoice                setChoice(string $val)                   Type: string(120)
 * @method MailingListMetaChoice                setMailingListMeta(MailingListMeta $val) 
 * @method MailingListMetaChoice                setContactMeta(Doctrine_Collection $val) 
 *  
 * @package    policat
 * @subpackage model
 * @author     Martin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMailingListMetaChoice extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mailing_list_meta_choice');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('mailing_list_meta_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('choice', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));


        $this->index('mlmc_choice', array(
             'fields' => 
             array(
              0 => 'choice',
             ),
             ));
        $this->index('mlmc_ml_choice', array(
             'fields' => 
             array(
              0 => 'mailing_list_meta_id',
              1 => 'choice',
             ),
             ));
        $this->option('symfony', array(
             'form' => true,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MailingListMeta', array(
             'local' => 'mailing_list_meta_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('ContactMeta', array(
             'local' => 'id',
             'foreign' => 'mailing_list_meta_choice_id'));
    }
}