<?php

/**
 * BaseOfferItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int        $id                  Type: integer(4), primary key
 * @property int        $offer_id            Type: integer(4)
 * @property string     $name                Type: string(120)
 * @property float      $price               Type: decimal(10)
 * @property int        $days                Type: integer(4)
 * @property int        $emails              Type: integer(4)
 * @property Offer      $Offer               
 *  
 * @method int          getId()              Type: integer(4), primary key
 * @method int          getOfferId()         Type: integer(4)
 * @method string       getName()            Type: string(120)
 * @method float        getPrice()           Type: decimal(10)
 * @method int          getDays()            Type: integer(4)
 * @method int          getEmails()          Type: integer(4)
 * @method Offer        getOffer()           
 *  
 * @method OfferItem    setId(int $val)      Type: integer(4), primary key
 * @method OfferItem    setOfferId(int $val) Type: integer(4)
 * @method OfferItem    setName(string $val) Type: string(120)
 * @method OfferItem    setPrice(float $val) Type: decimal(10)
 * @method OfferItem    setDays(int $val)    Type: integer(4)
 * @method OfferItem    setEmails(int $val)  Type: integer(4)
 * @method OfferItem    setOffer(Offer $val) 
 *  
 * @package    policat
 * @subpackage model
 * @author     Martin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOfferItem extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('offer_item');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('offer_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('price', 'decimal', 10, array(
             'type' => 'decimal',
             'notnull' => true,
             'scale' => 2,
             'length' => 10,
             ));
        $this->hasColumn('days', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('emails', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Offer', array(
             'local' => 'offer_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}