<?php

/**
 * BasePledgeText
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int           $pledge_item_id                    Type: integer(4), primary key
 * @property int           $petition_text_id                  Type: integer(4), primary key
 * @property string        $text                              Type: clob
 * @property PledgeItem    $PledgeItem                        
 * @property PetitionText  $PetitionText                      
 *  
 * @method int             getPledgeItemId()                  Type: integer(4), primary key
 * @method int             getPetitionTextId()                Type: integer(4), primary key
 * @method string          getText()                          Type: clob
 * @method PledgeItem      getPledgeItem()                    
 * @method PetitionText    getPetitionText()                  
 *  
 * @method PledgeText      setPledgeItemId(int $val)          Type: integer(4), primary key
 * @method PledgeText      setPetitionTextId(int $val)        Type: integer(4), primary key
 * @method PledgeText      setText(string $val)               Type: clob
 * @method PledgeText      setPledgeItem(PledgeItem $val)     
 * @method PledgeText      setPetitionText(PetitionText $val) 
 *  
 * @package    policat
 * @subpackage model
 * @author     Martin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePledgeText extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pledge_text');
        $this->hasColumn('pledge_item_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('petition_text_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('text', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));

        $this->option('form', true);
        $this->option('filter', false);
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PledgeItem', array(
             'local' => 'pledge_item_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('PetitionText', array(
             'local' => 'petition_text_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}