<?php

/**
 * BaseTicket
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int          $from_id                        Type: integer(4)
 * @property int          $to_id                          Type: integer(4)
 * @property int          $campaign_id                    Type: integer(4)
 * @property int          $petition_id                    Type: integer(4)
 * @property int          $widget_id                      Type: integer(4)
 * @property int          $target_list_id                 Type: integer(4)
 * @property int          $kind                           Type: integer(2), default "1"
 * @property int          $status                         Type: integer(1), default "1"
 * @property string       $text                           Type: clob
 * @property string       $data_json                      Type: clob
 * @property sfGuardUser  $From                           
 * @property sfGuardUser  $To                             
 * @property Campaign     $Campaign                       
 * @property Petition     $Petition                       
 * @property Widget       $Widget                         
 * @property MailingList  $TargetList                     
 *  
 * @method int            getFromId()                     Type: integer(4)
 * @method int            getToId()                       Type: integer(4)
 * @method int            getCampaignId()                 Type: integer(4)
 * @method int            getPetitionId()                 Type: integer(4)
 * @method int            getWidgetId()                   Type: integer(4)
 * @method int            getTargetListId()               Type: integer(4)
 * @method int            getKind()                       Type: integer(2), default "1"
 * @method int            getStatus()                     Type: integer(1), default "1"
 * @method string         getText()                       Type: clob
 * @method string         getDataJson()                   Type: clob
 * @method sfGuardUser    getFrom()                       
 * @method sfGuardUser    getTo()                         
 * @method Campaign       getCampaign()                   
 * @method Petition       getPetition()                   
 * @method Widget         getWidget()                     
 * @method MailingList    getTargetList()                 
 *  
 * @method Ticket         setFromId(int $val)             Type: integer(4)
 * @method Ticket         setToId(int $val)               Type: integer(4)
 * @method Ticket         setCampaignId(int $val)         Type: integer(4)
 * @method Ticket         setPetitionId(int $val)         Type: integer(4)
 * @method Ticket         setWidgetId(int $val)           Type: integer(4)
 * @method Ticket         setTargetListId(int $val)       Type: integer(4)
 * @method Ticket         setKind(int $val)               Type: integer(2), default "1"
 * @method Ticket         setStatus(int $val)             Type: integer(1), default "1"
 * @method Ticket         setText(string $val)            Type: clob
 * @method Ticket         setDataJson(string $val)        Type: clob
 * @method Ticket         setFrom(sfGuardUser $val)       
 * @method Ticket         setTo(sfGuardUser $val)         
 * @method Ticket         setCampaign(Campaign $val)      
 * @method Ticket         setPetition(Petition $val)      
 * @method Ticket         setWidget(Widget $val)          
 * @method Ticket         setTargetList(MailingList $val) 
 *  
 * @package    policat
 * @subpackage model
 * @author     Martin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTicket extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ticket');
        $this->hasColumn('from_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('to_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('campaign_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('petition_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('widget_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('target_list_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('kind', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             'length' => 2,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             'length' => 1,
             ));
        $this->hasColumn('text', 'clob', null, array(
             'type' => 'clob',
             'notnull' => false,
             ));
        $this->hasColumn('data_json', 'clob', null, array(
             'type' => 'clob',
             'notnull' => false,
             ));


        $this->index('ticket_kind_idx', array(
             'fields' => 
             array(
              0 => 'kind',
             ),
             ));
        $this->index('ticket_status_idx', array(
             'fields' => 
             array(
              0 => 'status',
             ),
             ));
        $this->option('options', NULL);
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as From', array(
             'local' => 'from_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('sfGuardUser as To', array(
             'local' => 'to_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Campaign', array(
             'local' => 'campaign_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Petition', array(
             'local' => 'petition_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Widget', array(
             'local' => 'widget_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('MailingList as TargetList', array(
             'local' => 'target_list_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}