<?php

/**
 * BaseMigrationVersion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int               $version             Type: integer(4)
 *  
 * @method int                 getVersion()         Type: integer(4)
 *  
 * @method MigrationVersion    setVersion(int $val) Type: integer(4)
 *  
 * @package    policat
 * @subpackage model
 * @author     Martin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMigrationVersion extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('migration_version');
        $this->hasColumn('version', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}