<?php

/**
 * BasePetitionSigningWave
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                  $id                                      Type: integer(8), primary key
 * @property int                  $petition_signing_id                     Type: integer(8), primary key
 * @property int                  $wave                                    Type: integer(2), default "1"
 * @property string               $fields                                  Type: clob
 * @property int                  $status                                  Type: integer(4), default "1"
 * @property string               $email                                   Type: string(80)
 * @property string               $country                                 Type: string(5)
 * @property string               $validation_data                         Type: string
 * @property string               $language_id                             Type: string(5)
 * @property int                  $widget_id                               Type: integer(4)
 * @property int                  $contact_num                             Type: integer(4)
 * @property PetitionSigning      $PetitionSigning                         
 * @property Widget               $Widget                                  
 * @property Language             $Language                                
 *  
 * @method int                    getId()                                  Type: integer(8), primary key
 * @method int                    getPetitionSigningId()                   Type: integer(8), primary key
 * @method int                    getWave()                                Type: integer(2), default "1"
 * @method string                 getFields()                              Type: clob
 * @method int                    getStatus()                              Type: integer(4), default "1"
 * @method string                 getEmail()                               Type: string(80)
 * @method string                 getCountry()                             Type: string(5)
 * @method string                 getValidationData()                      Type: string
 * @method string                 getLanguageId()                          Type: string(5)
 * @method int                    getWidgetId()                            Type: integer(4)
 * @method int                    getContactNum()                          Type: integer(4)
 * @method PetitionSigning        getPetitionSigning()                     
 * @method Widget                 getWidget()                              
 * @method Language               getLanguage()                            
 *  
 * @method PetitionSigningWave    setId(int $val)                          Type: integer(8), primary key
 * @method PetitionSigningWave    setPetitionSigningId(int $val)           Type: integer(8), primary key
 * @method PetitionSigningWave    setWave(int $val)                        Type: integer(2), default "1"
 * @method PetitionSigningWave    setFields(string $val)                   Type: clob
 * @method PetitionSigningWave    setStatus(int $val)                      Type: integer(4), default "1"
 * @method PetitionSigningWave    setEmail(string $val)                    Type: string(80)
 * @method PetitionSigningWave    setCountry(string $val)                  Type: string(5)
 * @method PetitionSigningWave    setValidationData(string $val)           Type: string
 * @method PetitionSigningWave    setLanguageId(string $val)               Type: string(5)
 * @method PetitionSigningWave    setWidgetId(int $val)                    Type: integer(4)
 * @method PetitionSigningWave    setContactNum(int $val)                  Type: integer(4)
 * @method PetitionSigningWave    setPetitionSigning(PetitionSigning $val) 
 * @method PetitionSigningWave    setWidget(Widget $val)                   
 * @method PetitionSigningWave    setLanguage(Language $val)               
 *  
 * @package    policat
 * @subpackage model
 * @author     Martin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePetitionSigningWave extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('petition_signing_wave');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('petition_signing_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('wave', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             'length' => 2,
             ));
        $this->hasColumn('fields', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('status', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             'length' => 4,
             ));
        $this->hasColumn('email', 'string', 80, array(
             'type' => 'string',
             'length' => 80,
             ));
        $this->hasColumn('country', 'string', 5, array(
             'type' => 'string',
             'length' => 5,
             ));
        $this->hasColumn('validation_data', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('language_id', 'string', 5, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 5,
             ));
        $this->hasColumn('widget_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('contact_num', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 4,
             ));


        $this->index('psw_wave', array(
             'fields' => 
             array(
              0 => 'wave',
             ),
             ));
        $this->index('psw_status', array(
             'fields' => 
             array(
              0 => 'status',
             ),
             ));
        $this->index('psw_p_status', array(
             'fields' => 
             array(
              0 => 'petition_signing_id',
              1 => 'status',
             ),
             ));
        $this->index('psw_p_w_status', array(
             'fields' => 
             array(
              0 => 'petition_signing_id',
              1 => 'wave',
              2 => 'status',
             ),
             ));
        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
        $this->option('non_json_fields', array(
             'fields' => 
             array(
              0 => 'email',
              1 => 'country',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PetitionSigning', array(
             'local' => 'petition_signing_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Widget', array(
             'local' => 'widget_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Language', array(
             'local' => 'language_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));
    }
}