<?php

/**
 * BaseMappingPair
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int          $id                      Type: integer(4), primary key
 * @property int          $mapping_id              Type: integer(4)
 * @property string       $a                       Type: string(80)
 * @property string       $b                       Type: string(80)
 * @property Mapping      $Mapping                 
 *  
 * @method int            getId()                  Type: integer(4), primary key
 * @method int            getMappingId()           Type: integer(4)
 * @method string         getA()                   Type: string(80)
 * @method string         getB()                   Type: string(80)
 * @method Mapping        getMapping()             
 *  
 * @method MappingPair    setId(int $val)          Type: integer(4), primary key
 * @method MappingPair    setMappingId(int $val)   Type: integer(4)
 * @method MappingPair    setA(string $val)        Type: string(80)
 * @method MappingPair    setB(string $val)        Type: string(80)
 * @method MappingPair    setMapping(Mapping $val) 
 *  
 * @package    policat
 * @subpackage model
 * @author     Martin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMappingPair extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mapping_pair');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('mapping_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('a', 'string', 80, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 80,
             ));
        $this->hasColumn('b', 'string', 80, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 80,
             ));


        $this->index('mp_a_idx', array(
             'fields' => 
             array(
              0 => 'mapping_id',
              1 => 'a',
             ),
             ));
        $this->index('mp_ab_idx', array(
             'fields' => 
             array(
              0 => 'mapping_id',
              1 => 'a',
              2 => 'b',
             ),
             'type' => 'unique',
             ));
        $this->option('form', false);
        $this->option('filter', false);
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Mapping', array(
             'local' => 'mapping_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $cachetaggable0 = new Doctrine_Template_Cachetaggable();
        $this->actAs($cachetaggable0);
    }
}