<?php

/**
 * BasePetitionSigningContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $petition_signing_id
 * @property integer $contact_id
 * @property integer $wave
 * @property PetitionSigning $PetitionSigning
 * @property Contact $Contact
 * 
 * @method integer                getPetitionSigningId()   Returns the current record's "petition_signing_id" value
 * @method integer                getContactId()           Returns the current record's "contact_id" value
 * @method integer                getWave()                Returns the current record's "wave" value
 * @method PetitionSigning        getPetitionSigning()     Returns the current record's "PetitionSigning" value
 * @method Contact                getContact()             Returns the current record's "Contact" value
 * @method PetitionSigningContact setPetitionSigningId()   Sets the current record's "petition_signing_id" value
 * @method PetitionSigningContact setContactId()           Sets the current record's "contact_id" value
 * @method PetitionSigningContact setWave()                Sets the current record's "wave" value
 * @method PetitionSigningContact setPetitionSigning()     Sets the current record's "PetitionSigning" value
 * @method PetitionSigningContact setContact()             Sets the current record's "Contact" value
 * 
 * @package    policat
 * @subpackage model
 * @author     Martin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePetitionSigningContact extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('petition_signing_contact');
        $this->hasColumn('petition_signing_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('contact_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('wave', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             'length' => 2,
             ));


        $this->index('psc_wave', array(
             'fields' => 
             array(
              0 => 'wave',
             ),
             ));
        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PetitionSigning', array(
             'local' => 'petition_signing_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Contact', array(
             'local' => 'contact_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}