<?php

/**
 * BaseCampaign
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                                       $id                                             Type: integer(4), primary key
 * @property string                                    $name                                           Type: string
 * @property int                                       $status                                         Type: integer(4), default "1"
 * @property int                                       $billing_enabled                                Type: integer(1)
 * @property int                                       $owner_register                                 Type: integer(4)
 * @property int                                       $allow_download                                 Type: integer(4)
 * @property int                                       $become_petition_admin                          Type: integer(4)
 * @property string                                    $privacy_policy                                 Type: clob
 * @property string                                    $address                                        Type: clob
 * @property int                                       $data_owner_id                                  Type: integer(4)
 * @property int                                       $quota_id                                       Type: integer(4)
 * @property int                                       $order_id                                       Type: integer(4)
 * @property int                                       $public_enabled                                 Type: integer(1)
 * @property int                                       $join_enabled                                   Type: integer(1)
 * @property Doctrine_Collection|sfGuardUser[]         $sfGuardUser                                    
 * @property sfGuardUser                               $DataOwner                                      
 * @property Order                                     $Order                                          
 * @property Quota                                     $Quota                                          
 * @property Doctrine_Collection|Member[]              $Member                                         
 * @property Doctrine_Collection|CampaignRights[]      $CampaignRights                                 
 * @property Doctrine_Collection|Petition[]            $Petition                                       
 * @property Doctrine_Collection|Widget[]              $Widget                                         
 * @property Doctrine_Collection|PetitionSigning[]     $PetitionSigning                                
 * @property Doctrine_Collection|MailingList[]         $MailingList                                    
 * @property Doctrine_Collection|Owner[]               $Owner                                          
 * @property Doctrine_Collection|Ticket[]              $Tickets                                        
 * @property Doctrine_Collection|CampaignStore[]       $CampaignStore                                  
 * @property Doctrine_Collection|Download[]            $Downloads                                      
 * @property Doctrine_Collection|Quota[]               $Quotas                                         
 * @property Offer                                     $Offer                                          
 * @property Doctrine_Collection|InvitationCampaign[]  $InvitationCampaign                             
 *  
 * @method int                                         getId()                                         Type: integer(4), primary key
 * @method string                                      getName()                                       Type: string
 * @method int                                         getStatus()                                     Type: integer(4), default "1"
 * @method int                                         getBillingEnabled()                             Type: integer(1)
 * @method int                                         getOwnerRegister()                              Type: integer(4)
 * @method int                                         getAllowDownload()                              Type: integer(4)
 * @method int                                         getBecomePetitionAdmin()                        Type: integer(4)
 * @method string                                      getPrivacyPolicy()                              Type: clob
 * @method string                                      getAddress()                                    Type: clob
 * @method int                                         getDataOwnerId()                                Type: integer(4)
 * @method int                                         getQuotaId()                                    Type: integer(4)
 * @method int                                         getOrderId()                                    Type: integer(4)
 * @method int                                         getPublicEnabled()                              Type: integer(1)
 * @method int                                         getJoinEnabled()                                Type: integer(1)
 * @method Doctrine_Collection|sfGuardUser[]           getSfGuardUser()                                
 * @method sfGuardUser                                 getDataOwner()                                  
 * @method Order                                       getOrder()                                      
 * @method Quota                                       getQuota()                                      
 * @method Doctrine_Collection|Member[]                getMember()                                     
 * @method Doctrine_Collection|CampaignRights[]        getCampaignRights()                             
 * @method Doctrine_Collection|Petition[]              getPetition()                                   
 * @method Doctrine_Collection|Widget[]                getWidget()                                     
 * @method Doctrine_Collection|PetitionSigning[]       getPetitionSigning()                            
 * @method Doctrine_Collection|MailingList[]           getMailingList()                                
 * @method Doctrine_Collection|Owner[]                 getOwner()                                      
 * @method Doctrine_Collection|Ticket[]                getTickets()                                    
 * @method Doctrine_Collection|CampaignStore[]         getCampaignStore()                              
 * @method Doctrine_Collection|Download[]              getDownloads()                                  
 * @method Doctrine_Collection|Quota[]                 getQuotas()                                     
 * @method Offer                                       getOffer()                                      
 * @method Doctrine_Collection|InvitationCampaign[]    getInvitationCampaign()                         
 *  
 * @method Campaign                                    setId(int $val)                                 Type: integer(4), primary key
 * @method Campaign                                    setName(string $val)                            Type: string
 * @method Campaign                                    setStatus(int $val)                             Type: integer(4), default "1"
 * @method Campaign                                    setBillingEnabled(int $val)                     Type: integer(1)
 * @method Campaign                                    setOwnerRegister(int $val)                      Type: integer(4)
 * @method Campaign                                    setAllowDownload(int $val)                      Type: integer(4)
 * @method Campaign                                    setBecomePetitionAdmin(int $val)                Type: integer(4)
 * @method Campaign                                    setPrivacyPolicy(string $val)                   Type: clob
 * @method Campaign                                    setAddress(string $val)                         Type: clob
 * @method Campaign                                    setDataOwnerId(int $val)                        Type: integer(4)
 * @method Campaign                                    setQuotaId(int $val)                            Type: integer(4)
 * @method Campaign                                    setOrderId(int $val)                            Type: integer(4)
 * @method Campaign                                    setPublicEnabled(int $val)                      Type: integer(1)
 * @method Campaign                                    setJoinEnabled(int $val)                        Type: integer(1)
 * @method Campaign                                    setSfGuardUser(Doctrine_Collection $val)        
 * @method Campaign                                    setDataOwner(sfGuardUser $val)                  
 * @method Campaign                                    setOrder(Order $val)                            
 * @method Campaign                                    setQuota(Quota $val)                            
 * @method Campaign                                    setMember(Doctrine_Collection $val)             
 * @method Campaign                                    setCampaignRights(Doctrine_Collection $val)     
 * @method Campaign                                    setPetition(Doctrine_Collection $val)           
 * @method Campaign                                    setWidget(Doctrine_Collection $val)             
 * @method Campaign                                    setPetitionSigning(Doctrine_Collection $val)    
 * @method Campaign                                    setMailingList(Doctrine_Collection $val)        
 * @method Campaign                                    setOwner(Doctrine_Collection $val)              
 * @method Campaign                                    setTickets(Doctrine_Collection $val)            
 * @method Campaign                                    setCampaignStore(Doctrine_Collection $val)      
 * @method Campaign                                    setDownloads(Doctrine_Collection $val)          
 * @method Campaign                                    setQuotas(Doctrine_Collection $val)             
 * @method Campaign                                    setOffer(Offer $val)                            
 * @method Campaign                                    setInvitationCampaign(Doctrine_Collection $val) 
 *  
 * @package    policat
 * @subpackage model
 * @author     Martin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCampaign extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('campaign');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('status', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             'length' => 4,
             ));
        $this->hasColumn('billing_enabled', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('owner_register', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('allow_download', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('become_petition_admin', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('privacy_policy', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('address', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('data_owner_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('quota_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('order_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('public_enabled', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('join_enabled', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 1,
             ));


        $this->index('campaign_status', array(
             'fields' => 
             array(
              0 => 'status',
             ),
             ));
        $this->index('campaign_name', array(
             'fields' => 
             array(
              'name' => 
              array(
              'length' => 100,
              ),
             ),
             ));
        $this->option('options', NULL);
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardUser', array(
             'refClass' => 'Member',
             'local' => 'campaign_id',
             'foreign' => 'sf_guard_user_id'));

        $this->hasOne('sfGuardUser as DataOwner', array(
             'local' => 'data_owner_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Order', array(
             'local' => 'order_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Quota', array(
             'local' => 'quota_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('Member', array(
             'local' => 'id',
             'foreign' => 'campaign_id'));

        $this->hasMany('CampaignRights', array(
             'local' => 'id',
             'foreign' => 'campaign_id'));

        $this->hasMany('Petition', array(
             'local' => 'id',
             'foreign' => 'campaign_id'));

        $this->hasMany('Widget', array(
             'local' => 'id',
             'foreign' => 'campaign_id'));

        $this->hasMany('PetitionSigning', array(
             'local' => 'id',
             'foreign' => 'campaign_id'));

        $this->hasMany('MailingList', array(
             'local' => 'id',
             'foreign' => 'campaign_id'));

        $this->hasMany('Owner', array(
             'local' => 'id',
             'foreign' => 'campaign_id'));

        $this->hasMany('Ticket as Tickets', array(
             'local' => 'id',
             'foreign' => 'campaign_id'));

        $this->hasMany('CampaignStore', array(
             'local' => 'id',
             'foreign' => 'campaign_id'));

        $this->hasMany('Download as Downloads', array(
             'local' => 'id',
             'foreign' => 'campaign_id'));

        $this->hasMany('Quota as Quotas', array(
             'local' => 'id',
             'foreign' => 'campaign_id'));

        $this->hasOne('Offer', array(
             'local' => 'id',
             'foreign' => 'campaign_id'));

        $this->hasMany('InvitationCampaign', array(
             'local' => 'id',
             'foreign' => 'campaign_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $cachetaggable0 = new Doctrine_Template_Cachetaggable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($cachetaggable0);
    }
}