#!/bin/bash
set -e

if [ ! -z "$PHP_MAIL_FROM" ]; then
	sed -i "s/john.doe@example.com/${PHP_MAIL_FROM}/" /usr/local/etc/php/conf.d/sendmail.ini
fi

if [ ! -z "$PHP_MAIL_HOST" ]; then
	sed -i "s/--host=mail/--host=${PHP_MAIL_HOST}/" /usr/local/etc/php/conf.d/sendmail.ini
fi

mkdir -p /app/data/upload_tmp
mkdir -p /app/data/session

if [ ! -z "$WWW_DATA_UID" ]; then
	echo "www-data uid => ${WWW_DATA_UID}"
	usermod -u ${WWW_DATA_UID} www-data
	if [ ! -z "$WWW_DATA_GID" ]; then
		echo "www-data gid => ${WWW_DATA_GID}"
		groupmod -g ${WWW_DATA_GID} www-data
	fi
	chown -R www-data:www-data /var/lock/apache2 /var/run/apache2 /var/log/apache2
fi

chown -R www-data:www-data /app/data/csv_uploads /app/data/csv_downloads /app/web/images/keyvisual /app/web/images/pledge_header_visual /app/web/images/pledge_key_visual /app/web/images/store
chown -R www-data:www-data /app/cache /app/log

exec /usr/local/bin/apache2-foreground
