<?php
/*
 * Copyright (c) 2016, webvariants GmbH <?php Co. KG, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

/**
 * BillTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BillTable extends Doctrine_Table {

  /**
   * Returns an instance of this class.
   *
   * @return BillTable The table instance
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('Bill');
  }

  public function bill(Order $order, $connection = null) {
    $con = $connection ? : $this->getConnection();
    try {
      $con->beginTransaction();

      $bill = $order->getBill();
      $bill->setUser($order->getUser());
      $order->fillBill($bill);
      $bill->save();

      $markup = strtr(UtilMarkdown::transform(strtr(StoreTable::value(StoreTable::BILLING_BILL), $bill->getSubst1()), false), $bill->getSubst2());
      $bill->setMarkup($markup);
      $bill->save();

      $con->commit();
      return true;
    } catch (\Exception $e) {
      $con->rollback();
      return false;
    }
  }

}
