<?php

/**
 * Campaign
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    policat
 * @subpackage model
 * @author     Martin
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Campaign extends BaseCampaign
{
  const OWNER_REGISTER_NO = 0;
  const OWNER_REGISTER_YES = 1;

  public static $OWNER_REGISTER_SHOW = array(
    self::OWNER_REGISTER_NO => 'off',
    self::OWNER_REGISTER_YES => 'on'
  );

  const ALLOW_DOWNLOAD_NO = 0;
  const ALLOW_DOWNLOAD_YES = 1;

  public static $ALLOW_DOWNLOAD_SHOW = array(
    self::ALLOW_DOWNLOAD_NO => 'no',
    self::ALLOW_DOWNLOAD_YES => 'yes'
  );
  
  const BECOME_PETITION_ADMIN_NO = 0;
  const BECOME_PETITION_ADMIN_YES = 1;

  public static $BECOME_PETITION_ADMIN_SHOW = array(
    self::BECOME_PETITION_ADMIN_NO => 'off',
    self::BECOME_PETITION_ADMIN_YES => 'on'
  );
  
  public function isEditableBy(sfGuardUser $user) {
    return $user->isCampaignAdmin($this);
  }
}