<?php

/**
 * ContactMetaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContactMetaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContactMetaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContactMeta');
    }
}