<?php
/*
 * Copyright (c) 2015, webvariants GmbH & Co. KG, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

/**
 * Download
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    policat
 * @subpackage model
 * @author     Martin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Download extends BaseDownload {

  public function getIdForType() {
    switch ($this->getType()) {
      case 'petition':
        return $this->getPetitionId();
      case 'campaign':
        return $this->getCampaignId();
      case 'widget':
        return $this->getWidgetId();
    }
  }

  public function getFilepath() {
    return self::buildFilepath($this->getFilename());
  }

  private static function buildFilepath($filename) {
    $dir = sfConfig::get('sf_data_dir') . '/csv_downloads';
    @mkdir($dir, 0777, true);
    return $dir . '/' . $filename;
  }

  public function getDownloadFilename() {
    $ret = '';

    if ($this->getCampaignId()) {
      $ret .= 'Campaign_' . $this->getCampaignId() . '_';
    }

    if ($this->getPetitionId()) {
      $ret .= 'Petition_' . $this->getPetitionId() . '_';
    }

    if ($this->getWidgetId()) {
      $ret .= 'Widget_' . $this->getWidgetId() . '_';
    }

    return $ret . strtr($this->getCreatedAt(), ' ', '_') . '.csv';
  }

}
