<?php

/**
 * InvitationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InvitationTable extends Doctrine_Table {

  /**
   * Returns an instance of this class.
   *
   * @return InvitationTable The table instance
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('Invitation');
  }

  public function findByEmail($email) {
    return $this->createQuery('i')->where('i.email_address = ?', array($email))->fetchOne();
  }

}
