<?php

/**
 * Language
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    policat
 * @subpackage model
 * @author     Martin
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Language extends BaseLanguage {

  static function i18nPathWidget() {
    return strtr(sfConfig::get('sf_app_i18n_dir'), array('/apps/frontend/' => '/apps/widget/'));
  }

  public function i18nFileWidget() {
    return self::i18nPathWidget() . '/' . $this->getId() . '/messages.xml';
  }

  static function i18nCachePathWidget() {
    return strtr(sfConfig::get('sf_i18n_cache_dir'), array('/cache/frontend/' => '/cache/widget/'));
  }

  public function i18nCacheWidgetClear() {
    foreach (scandir(self::i18nCachePathWidget()) as $dir)
      if (substr($dir, - strlen($this->getId())) == $this->getId()) { // find language
        if (file_exists(self::i18nCachePathWidget() . '/' . $dir . '/messages.xml'))
          foreach (scandir(self::i18nCachePathWidget() . '/' . $dir . '/messages.xml') as $cache_file) {
            @unlink(self::i18nCachePathWidget() . '/' . $dir . '/messages.xml/' . $cache_file);
          }
      }
  }

}