<?php

/**
 * MailingListMetaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MailingListMetaTable extends Doctrine_Table {

  /**
   * Returns an instance of this class.
   *
   * @return MailingListMetaTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('MailingListMeta');
  }

  /**
   *
   * @param int $id
   * @return MailingListMeta
   */
  public function findOneById($id) {
    return $this->findOneBy('id', $id);
  }

  /**
   *
   * @param MailingList $mailing_list
   * @return Doctrine_Query
   */
  public function queryByMailingList(MailingList $mailing_list) {
    return $this->createQuery('mlm')->where('mlm.mailing_list_id = ?', $mailing_list->getId());
  }

  /**
   *
   * @param MailingList $mailing_list
   * @return Doctrine_Query
   */
  public function queryByMailingListChoice(MailingList $mailing_list) {
    return $this->createQuery('mlm')->where('mlm.mailing_list_id = ?', $mailing_list->getId())->andWhere('mlm.kind = ?', MailingListMeta::KIND_CHOICE);
  }

}