<?php

/**
 * MediaFilesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MediaFilesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return MediaFilesTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MediaFiles');
    }
    
   /**
   *
   * @return Doctrine_Query
   */
  public function queryAll() {
    return $this->createQuery('w')->orderBy('w.created_at DESC');
  }
    
  /**
   *
   * @param Petition $petition
   * @return Doctrine_Query
   */
  public function queryByPetition($petitionId) {
    return $this->queryAll()->where('w.petition_id = ?', $petitionId);
  }
  
  /**
   *
   * @param Petition $petition
   * @return Doctrine_Query
   */
  public function queryByPetitionAndId($petitionId,$id) {
    return $this->queryAll()->where('w.petition_id = ? and w.id=?', array($petitionId,$id))->fetchOne();
  }
}