<?php
/*
 * Copyright (c) 2016, webvariants GmbH <?php Co. KG, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

/**
 * Order
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    policat
 * @subpackage model
 * @author     Martin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Order extends BaseOrder {

  public function deleteable() {
    $status = $this->getStatus();

    $quota = $this->getQuotas()->getFirst();
    /* @var $quota Quota */

    return $status == OrderTable::STATUS_ORDER && $status != OrderTable::STATUS_PAID && $quota->getEmailsDone() <= 0 && $this->getBill()->isNew();
  }

  public function fillByOrder(Order $order) {
    $this->setStatus(OrderTable::STATUS_ORDER);
    $this->setUser($order->getUser());
    $this->setFirstName($order->getFirstName());
    $this->setLastName($order->getLastName());
    $this->setOrganisation($order->getOrganisation());
    $this->setStreet($order->getStreet());
    $this->setCity($order->getCity());
    $this->setPostCode($order->getPostCode());
    $this->setCountry($order->getCountry());
    $this->setVat($order->getVat());
    $this->setTax(CountryTaxTable::taxForCountryVat($this->getCountry(), trim($this->getVat())));
    $this->setTaxNote(CountryTaxTable::noteForCountryVat($this->getCountry(), trim($this->getVat())));
  }

  public function fillBill(\BillInterface $bill) {

    $bill->setFirstName($this->getFirstName());
    $bill->setLastName($this->getLastName());
    $bill->setOrganisation($this->getOrganisation());
    $bill->setStreet($this->getStreet());
    $bill->setCity($this->getCity());
    $bill->setPostCode($this->getPostCode());
    $bill->setCountry($this->getCountry());
    $bill->setVat($this->getVat());
    $bill->setTax($this->getTax());
    $bill->setTaxNote($this->getTaxNote());
    $price = 0;



    foreach ($this->getQuotas() as $quota) {
      /* @var $quota Quota */
      $bill->addItemByQuota($quota);
      $price += $quota->getPrice();
    }

    $bill->setPrice($price);
    $bill->setPriceBrutto(round($price * (($bill->getTax() ? : 0) + 100) / 100, 2));
  }

}
