<?php
/*
 * Copyright (c) 2015, webvariants GmbH & Co. KG, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

/**
 * Owner
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    policat
 * @subpackage model
 * @author     Martin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Owner extends BaseOwner
{
  const STATUS_NEW = 1;
  const STATUS_APPROVED = 2;
  const STATUS_BLOCKED = 3;

  public static $STATUS_SHOW = array(
    self::STATUS_NEW => 'new',
    self::STATUS_APPROVED => 'approved',
    self::STATUS_BLOCKED => 'blocked'
  );
}
