<?php

/**
 * OwnerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OwnerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OwnerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Owner');
    }
}