<?php

/**
 * Permission
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    policat
 * @subpackage model
 * @author     Martin
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Permission extends BasePermission
{
  const NAME_PETITION_CREATE             = 'petition_create';
  const NAME_PETITION_APPROVAL           = 'petition_approval';
  const NAME_PETITION_REDRAFT            = 'petition_redraft';
  const NAME_PETITION_ACTIVATE           = 'petition_activate';
  const NAME_PETITION_BLOCK              = 'petition_block';
  const NAME_PETITION_EDIT_DRAFT         = 'petition_edit_draft';
  const NAME_PETITION_EDIT_ACTIVE        = 'petition_edit_active';
  const NAME_PETITION_EDIT_ALL           = 'petition_edit_all';

  const NAME_PETITION_TEXT_CREATE        = 'petition_text_create';
  const NAME_PETITION_TEXT_APPROVAL      = 'petition_text_approval';
  const NAME_PETITION_TEXT_REDRAFT       = 'petition_text_redraft';
  const NAME_PETITION_TEXT_ACTIVATE      = 'petition_text_activate';
  const NAME_PETITION_TEXT_BLOCK         = 'petition_text_block';
  const NAME_PETITION_TEXT_EDIT_DRAFT    = 'petition_text_edit_draft';
  const NAME_PETITION_TEXT_EDIT_ACTIVE   = 'petition_text_edit_active';
  const NAME_PETITION_TEXT_EDIT_ALL      = 'petition_text_edit_all';

  const NAME_WIDGET_CREATE               = 'widget_create';
  const NAME_WIDGET_BLOCK                = 'widget_block';
  const NAME_WIDGET_EDIT_DRAFT           = 'widget_edit_draft';
  const NAME_WIDGET_EDIT_ACTIVE          = 'widget_edit_active';
  const NAME_WIDGET_EDIT_ALL             = 'widget_edit_all';

  const NAME_PETITION_SIGNING_LIST       = 'petition_signing_list';
  const NAME_PETITION_SIGNING_MOD        = 'petition_signing_mod';

  const NAME_MEMBER_USER_ADMIN           = 'member_user_admin';
  const NAME_MEMBER_RIGHTS_ADMIN         = 'member_rights_admin';

  const NAME_MAILING_LIST_ALL            = 'mailing_list_all';

  static $NAMES = array(
    self::NAME_PETITION_CREATE,
    self::NAME_PETITION_APPROVAL,
    self::NAME_PETITION_REDRAFT,
    self::NAME_PETITION_ACTIVATE,
    self::NAME_PETITION_BLOCK,
    self::NAME_PETITION_EDIT_DRAFT,
    self::NAME_PETITION_EDIT_ALL,

    self::NAME_PETITION_TEXT_CREATE,
    self::NAME_PETITION_TEXT_APPROVAL,
    self::NAME_PETITION_TEXT_REDRAFT,
    self::NAME_PETITION_TEXT_ACTIVATE,
    self::NAME_PETITION_TEXT_BLOCK,
    self::NAME_PETITION_TEXT_EDIT_DRAFT,
    self::NAME_PETITION_TEXT_EDIT_ALL,

    self::NAME_WIDGET_CREATE,
    self::NAME_WIDGET_BLOCK,
    self::NAME_WIDGET_EDIT_DRAFT,
    self::NAME_WIDGET_EDIT_ALL,

    self::NAME_PETITION_SIGNING_LIST,
    self::NAME_PETITION_SIGNING_MOD,

    self::NAME_MEMBER_USER_ADMIN,
    self::NAME_MEMBER_RIGHTS_ADMIN,

    self::NAME_MAILING_LIST_ALL
  );
}