<?php
/*
 * Copyright (c) 2015, webvariants GmbH & Co. KG, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

/**
 * PetitionSigningWaveTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PetitionSigningWaveTable extends Doctrine_Table {

  /**
   * Returns an instance of this class.
   *
   * @return PetitionSigningWaveTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('PetitionSigningWave');
  }

  public function sumContactStatus($status, Petition $petition = null) {
    $query = self::getInstance()->createQuery('psw')
      ->select('SUM(psw.contact_num) as contact_num_sum')
      ->where('psw.status = ?', $status);
    if ($petition) {
      $query->leftJoin('psw.PetitionSigning ps')->andWhere('ps.petition_id = ?', $petition->getId());
    }

    $result = $query->fetchArray();
    if (isset($result[0])) {
      $num = $result[0]['contact_num_sum'];
      return $num ? $num : 0;
    }
    return 0;
  }

}
