<?php
/*
 * Copyright (c) 2015, webvariants GmbH & Co. KG, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

/**
 * PetitionContactTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PetitionContactTable extends Doctrine_Table {

  const CRYPT_ALGO = '$6$rounds=5000$';

  /**
   * Returns an instance of this class.
   *
   * @return PetitionContactTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('PetitionContact');
  }

  /**
   *
   * @param int $petition_id
   * @param int $contact_id
   * @param int $hydrationMode
   * @return PetitionContact
   */
  public function findOneByPetitionIdAndContactId($petition_id, $contact_id, $hydrationMode = null) {
    return $this->createQuery('pc')->where('pc.petition_id = ?', $petition_id)->andWhere('pc.contact_id = ?', $contact_id)->fetchOne($hydrationMode);
  }

  public static function salt() {
    $salt = '';
    while (strlen($salt) < 16) {
      $salt .= base_convert(mt_rand(), 10, 36);
    }
    return substr($salt, 0, 16);
  }

  public function queryByPetition($petition_id) {
    return $this->createQuery('pc INDEXBY pc.contact_id')->where('pc.petition_id = ?', $petition_id);
  }

}
