<?php

/**
 * PetitionContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    policat
 * @subpackage model
 * @author     Martin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PetitionContact extends BasePetitionContact {

  public function setHashPassword($password) {
    $this->setPassword(crypt($password, PetitionContactTable::CRYPT_ALGO . PetitionContactTable::salt()));
  }

  public function checkPassword($password) {
    $crypt = $this->getPassword();
    if ($crypt) {
      return $crypt === crypt($password, $crypt);
    }

    return false;
  }

}
