<?php

/**
 * PledgeItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PledgeItemTable extends Doctrine_Table {

  const STATUS_DRAFT = 0;
  const STATUS_ACTIVE = 2;
  const STATUS_CLOSED = 1;

  static $STATUS_SHOW = array(
      self::STATUS_DRAFT => 'draft',
      self::STATUS_ACTIVE => 'active',
      self::STATUS_CLOSED => 'closed'
  );

  /**
   * Returns an instance of this class.
   *
   * @return PledgeItemTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('PledgeItem');
  }

  public function fetchByIds($ids) {
    $ret = array();
    foreach ($this->createQuery('pi')->whereIn('pi.id', $ids)->execute() as $pledge_item) {
      /* @var $pledge_item PledgeItem */
      $ret[$pledge_item->getId()] = $pledge_item;
    }
    return $ret;
  }

}
