<?php

/**
 * PledgeItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    policat
 * @subpackage model
 * @author     Martin
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PledgeItem extends BasePledgeItem {

  public function getStatusName() {
    return PledgeItemTable::$STATUS_SHOW[$this->getStatus()];
  }

  public function countPledgeStatus($status, $target_list = null) {
    return PledgeTable::getInstance()->countStatus($this, $status, $this->getPetition()->getMailingList());
  }

}
