<?php

/**
 * StoreTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StoreTable extends Doctrine_Table {

  const PORTAL_NAME = 'portal_name';
  const PORTAL_LOGO = 'portal_logo';
  const PORTAL_META_DESCRIPTION = 'portal_description';
  const PORTAL_META_KEYWORDS = 'portal_keywords';
  const PORTAL_HOME_TITLE = 'portal_home_title';
  const PORTAL_HOME_MARKUP = 'portal_home_markup';
  const EMAIL_ADDRESS = 'email_address';
  const EMAIL_NAME = 'email_name';
  const EMAIL_SENDER = 'email_sender';
  const TERMS_TITLE = 'terms_title';
  const TERMS_CONTENT = 'terms_content';
  const TERMS_FOOTER = 'terms_footer';
  const CONTACT_TITLE = 'contact_title';
  const CONTACT_CONTENT = 'contact_content';
  const CONTACT_FOOTER = 'contact_footer';
  const IMPRINT_TITLE = 'imprint_title';
  const IMPRINT_CONTENT = 'imprint_content';
  const IMPRINT_FOOTER = 'imprint_footer';
  const FOOTER_TITLE = 'footer_title';
  const FOOTER_LINK = 'footer_link';
  const TIPS_TITLE = 'tips_title';
  const TIPS_CONTENT = 'tips_content';
  const TIPS_MENU = 'tips_menu';
  const FAQ_TITLE = 'faq_title';
  const FAQ_CONTENT = 'faq_content';
  const FAQ_MENU = 'faq_menu';
  const HELP_TITLE = 'help_title';
  const HELP_CONTENT = 'help_content';
  const HELP_MENU = 'help_menu';
  const MENU_HOME = 'menu_home';
  const MENU_START = 'menu_start';
  const MENU_LOGIN = 'menu_login';
  const MENU_JOIN = 'menu_join';
  const SIGNING_VALIDATION_EMAIL = 'signing_validation_email';
  const ACTION_TELL_YOUR_FRIEND_EMAIL = 'action_tellyourfriend_email';
  const ACTION_PRIVACY_POLICY = 'action_privacy_policy';
  const REGISTER_ON = 'register_on';
  const CAMAPIGN_CREATE_ON = 'campaign_create_on';
  const REGISTER_MAIL = 'register_mail';
  const PASSWORD_FORGOTTEN_MAIL = 'password_forgotten_mail';
  const EMBED_WIDGET_MAIL = 'embed_widget_mail';
  const NEW_USER_ADMIN_MAIL = 'new_user_admin_mail';
  const PRIVACY_AGREEMENT = 'privacy_agreement';
  const PRIVACY_AGREEMENT_EMAIL = 'privacy_agreement_email';
  const PRIVACY_AGREEMENT_REPLY = 'privacy_agreement_reply';
  const DONATIONS_PAYPAL = 'donations_paypal';
  
  static $meta = array(
      'portal' => array(
          'name' => 'Portal',
          'fields' => array(
              self::PORTAL_NAME => array(
                  'widget' => array('sfWidgetFormInputText', array('label' => 'Name')),
                  'validator' => array('sfValidatorString', array('max_length' => 40)),
              ),
              self::PORTAL_LOGO => array(
                  'widget' => array('WidgetLogo', array('label' => 'Logo')),
                  'validator' => array('ValidatorLogo', array('required' => false)),
                  'file' => true
              ),
              self::PORTAL_META_DESCRIPTION => array(
                  'widget' => array('sfWidgetFormInputText', array('label' => 'Description (Meta)')),
                  'validator' => array('sfValidatorString', array('max_length' => 80, 'required' => false)),
              ),
              self::PORTAL_META_KEYWORDS => array(
                  'widget' => array('sfWidgetFormInputText', array('label' => 'Keywords (Meta)')),
                  'validator' => array('sfValidatorString', array('max_length' => 80, 'required' => false)),
              ),
              self::DONATIONS_PAYPAL => array(
                  'widget' => array('WidgetBoolean', array('label' => 'Enable Donations via Paypal')),
                  'validator' => array('sfValidatorBoolean')
              ),
              self::PORTAL_HOME_TITLE => array(
                  'widget' => array('sfWidgetFormInputText', array('label' => 'Home title')),
                  'validator' => array('sfValidatorString', array('max_length' => 80, 'required' => false)),
              ),
              self::PORTAL_HOME_MARKUP => array(
                  'widget' => array('sfWidgetFormTextarea', array('label' => 'Home content'), array('class' => 'markdown')),
                  'validator' => array('sfValidatorString', array('required' => false)),
                  'help' => '#WIDGET-n# (Widget ID), #KEYVISUAL-n# (Action ID)'
              ),
          )
      ),
      'contact' => array(
          'name' => 'Contact',
          'fields' => array(
              self::CONTACT_TITLE => array(
                  'widget' => array('sfWidgetFormInputText', array('label' => 'Title')),
                  'validator' => array('sfValidatorString', array()),
              ),
              self::CONTACT_CONTENT => array(
                  'widget' => array('sfWidgetFormTextarea', array('label' => 'Content'), array('class' => 'markdown')),
                  'validator' => array('sfValidatorString', array()),
              ),
              self::CONTACT_FOOTER => array(
                  'widget' => array('WidgetBoolean', array('label' => 'Link in footer')),
                  'validator' => array('sfValidatorBoolean')
              )
          )
      ),
      'imprint' => array(
          'name' => 'Imprint',
          'fields' => array(
              self::IMPRINT_TITLE => array(
                  'widget' => array('sfWidgetFormInputText', array('label' => 'Title')),
                  'validator' => array('sfValidatorString', array()),
              ),
              self::IMPRINT_CONTENT => array(
                  'widget' => array('sfWidgetFormTextarea', array('label' => 'Content'), array('class' => 'markdown')),
                  'validator' => array('sfValidatorString', array()),
              ),
              self::IMPRINT_FOOTER => array(
                  'widget' => array('WidgetBoolean', array('label' => 'Link in footer')),
                  'validator' => array('sfValidatorBoolean')
              )
          )
      ),
      'footer' => array(
          'name' => 'Footer',
          'fields' => array(
              self::FOOTER_TITLE => array(
                  'widget' => array('sfWidgetFormInputText', array('label' => 'Title')),
                  'validator' => array('sfValidatorString', array()),
              ),
              self::FOOTER_LINK => array(
                  'widget' => array('sfWidgetFormInputText', array('label' => 'Link')),
                  'validator' => array('sfValidatorString', array('required' => false)),
              )
          )
      ),
      'email' => array(
          'name' => 'Mail-Address',
          'fields' => array(
              self::EMAIL_NAME => array(
                  'widget' => array('sfWidgetFormInputText', array('label' => 'Name')),
                  'validator' => array('sfValidatorString', array()),
//                  'help' => ''
              ),
              self::EMAIL_ADDRESS => array(
                  'widget' => array('sfWidgetFormInputText', array('label' => 'Email')),
                  'validator' => array('ValidatorEmail', array()),
              ),
              self::EMAIL_SENDER => array(
                  'widget' => array('WidgetBoolean', array('label' => 'Use as "Sender" for Action E-mails')),
                  'validator' => array('sfValidatorBoolean')
              )
          )
      ),
      'menu' => array(
          'name' => 'Menu',
          'fields' => array(
              self::MENU_HOME => array(
                  'widget' => array('WidgetBoolean', array('label' => 'Show "Home"')),
                  'validator' => array('sfValidatorBoolean')
              ),
              self::MENU_START => array(
                  'widget' => array('WidgetBoolean', array('label' => 'Show "Start an e-action"')),
                  'validator' => array('sfValidatorBoolean')
              ),
              self::MENU_JOIN => array(
                  'widget' => array('WidgetBoolean', array('label' => 'Show "Join"')),
                  'validator' => array('sfValidatorBoolean')
              ),
              self::MENU_LOGIN => array(
                  'widget' => array('WidgetBoolean', array('label' => 'Show "Login"')),
                  'validator' => array('sfValidatorBoolean')
              )
          )
      ),
      'register' => array(
          'name' => 'Registration',
          'fields' => array(
              self::REGISTER_ON => array(
                  'widget' => array('WidgetBoolean', array('label' => 'enabled')),
                  'validator' => array('sfValidatorBoolean')
              )
          )
      ),
      'campaign' => array(
          'name' => 'Campaign',
          'fields' => array(
              self::CAMAPIGN_CREATE_ON => array(
                  'widget' => array('WidgetBoolean', array('label' => 'creation enabled')),
                  'validator' => array('sfValidatorBoolean')
              )
          )
      ),
      'terms' => array(
          'name' => 'Terms of Service',
          'fields' => array(
              self::TERMS_TITLE => array(
                  'widget' => array('sfWidgetFormInputText', array('label' => 'Title')),
                  'validator' => array('sfValidatorString', array()),
              ),
              self::TERMS_CONTENT => array(
                  'widget' => array('sfWidgetFormTextarea', array('label' => 'Content'), array('class' => 'markdown')),
                  'validator' => array('sfValidatorString', array()),
              ),
              self::TERMS_FOOTER => array(
                  'widget' => array('WidgetBoolean', array('label' => 'Link in footer')),
                  'validator' => array('sfValidatorBoolean')
              )
          )
      ),
      'tips' => array(
          'name' => 'Tips and Guides',
          'fields' => array(
              self::TIPS_TITLE => array(
                  'widget' => array('sfWidgetFormInputText', array('label' => 'Title')),
                  'validator' => array('sfValidatorString', array()),
              ),
              self::TIPS_CONTENT => array(
                  'widget' => array('sfWidgetFormTextarea', array('label' => 'Content'), array('class' => 'markdown')),
                  'validator' => array('sfValidatorString', array()),
              ),
              self::TIPS_MENU => array(
                  'widget' => array('WidgetBoolean', array('label' => 'Link in menu')),
                  'validator' => array('sfValidatorBoolean')
              )
          )
      ),
      'faq' => array(
          'name' => 'FAQ',
          'fields' => array(
              self::FAQ_TITLE => array(
                  'widget' => array('sfWidgetFormInputText', array('label' => 'Title')),
                  'validator' => array('sfValidatorString', array()),
              ),
              self::FAQ_CONTENT => array(
                  'widget' => array('sfWidgetFormTextarea', array('label' => 'Content'), array('class' => 'markdown')),
                  'validator' => array('sfValidatorString', array()),
              ),
              self::FAQ_MENU => array(
                  'widget' => array('WidgetBoolean', array('label' => 'Link in menu')),
                  'validator' => array('sfValidatorBoolean')
              )
          )
      ),
      'help' => array(
          'name' => 'Help',
          'fields' => array(
              self::HELP_TITLE => array(
                  'widget' => array('sfWidgetFormInputText', array('label' => 'Title')),
                  'validator' => array('sfValidatorString', array()),
              ),
              self::HELP_CONTENT => array(
                  'widget' => array('sfWidgetFormTextarea', array('label' => 'Content'), array('class' => 'markdown')),
                  'validator' => array('sfValidatorString', array()),
              ),
              self::HELP_MENU => array(
                  'widget' => array('WidgetBoolean', array('label' => 'Link in menu')),
                  'validator' => array('sfValidatorBoolean')
              )
          )
      ),
      'signing_validation' => array(
          'name' => 'Default Signing Validation Mail',
          'json' => self::SIGNING_VALIDATION_EMAIL,
          'i18n' => true,
          'fields' => array(
              'subject' => array(
                  'widget' => array('sfWidgetFormInputText', array('label' => 'Subject'), array('class' => 'span7')),
                  'validator' => array('sfValidatorString', array('max_length' => 120)),
              ),
              'body' => array(
                  'widget' => array('sfWidgetFormTextarea', array('label' => 'Body'), array('class' => 'span7 elastic highlight')),
                  'validator' => array('ValidatorKeywords', array('keywords' => array('#VALIDATION-URL#'))),
                  'help' => '#VALIDATION-URL#, #REFERER-URL#, #READMORE-URL#, #TITLE#, #TARGET#, #BACKGROUND#, #INTRO#, #FOOTER#, #EMAIL-SUBJECT#, #EMAIL-BODY#, #BODY#'
              ),
          )
      ),
      'action_terms' => array(
          'name' => 'Default Privacy Policy',
          'json' => self::ACTION_PRIVACY_POLICY,
          'i18n' => true,
          'fields' => array(
              'body' => array(
                  'widget' => array('sfWidgetFormTextarea', array('label' => 'Text'), array('class' => 'markdown')),
                  'validator' => array('sfValidatorString', array()),
                  'help' => '#DATA-OFFICER-NAME#, #DATA-OFFICER-ORGA#, #DATA-OFFICER-EMAIL#, #DATA-OFFICER-WEBSITE#, #DATA-OFFICER-PHONE#, #DATA-OFFICER-MOBILE#, #DATA-OFFICER-STREET#, #DATA-OFFICER-POST-CODE#, #DATA-OFFICER-CITY#, #DATA-OFFICER-COUNTRY#, #DATA-OFFICER-ADDRESS#'
              ),
          )
      ),
      'tell_your_friend' => array(
          'name' => 'Default Tell-your-friend Mail',
          'json' => self::ACTION_TELL_YOUR_FRIEND_EMAIL,
          'i18n' => true,
          'fields' => array(
              'subject' => array(
                  'widget' => array('sfWidgetFormInputText', array('label' => 'Subject'), array('class' => 'span7')),
                  'validator' => array('sfValidatorString', array('max_length' => 120)),
              ),
              'body' => array(
                  'widget' => array('sfWidgetFormTextarea', array('label' => 'Body'), array('class' => 'span7 elastic')),
                  'validator' => array('sfValidatorString', array()),
              ),
          )
      ),
      'privacy_agreement' => array(
          'name' => 'Default Privacy Agreement Text',
          'json' => self::PRIVACY_AGREEMENT,
          'fields' => array(
              'text' => array(
                  'widget' => array('sfWidgetFormTextarea', array('label' => 'Text'), array('class' => 'span7 elastic highlight')),
                  'validator' => array('sfValidatorString', array())
              ),
          )
      ),
      'embed_widget_mail' => array(
          'name' => 'Embed widget verification mail',
          'json' => self::EMBED_WIDGET_MAIL,
          'i18n' => true,
          'fields' => array(
              'subject' => array(
                  'widget' => array('sfWidgetFormInputText', array('label' => 'Subject'), array('class' => 'span7')),
                  'validator' => array('sfValidatorString', array('max_length' => 120)),
              ),
              'body' => array(
                  'widget' => array('sfWidgetFormTextarea', array('label' => 'Body'), array('class' => 'span7 elastic highlight')),
                  'validator' => array('ValidatorKeywords', array('keywords' => array('#VALIDATION-URL#', '#EDIT-URL#'))),
                  'help' => '#VALIDATION-URL#, #EDIT-URL#'
              ),
          )
      ),
      'new_user_admin_mail' => array(
          'name' => 'New user by admin verification mail',
          'json' => self::NEW_USER_ADMIN_MAIL,
          'i18n' => true,
          'fields' => array(
              'subject' => array(
                  'widget' => array('sfWidgetFormInputText', array('label' => 'Subject'), array('class' => 'span7')),
                  'validator' => array('sfValidatorString', array('max_length' => 120)),
              ),
              'body' => array(
                  'widget' => array('sfWidgetFormTextarea', array('label' => 'Body'), array('class' => 'span7 elastic highlight')),
                  'validator' => array('ValidatorKeywords', array('keywords' => array('#VALIDATION-URL#'))),
                  'help' => '#VALIDATION-URL#, #USER-NAME#'
              ),
          )
      ),
      'privacy_agreement_email' => array(
          'name' => 'Privacy Agreement Email (for all Campaigns) UNUSED',
          'json' => self::PRIVACY_AGREEMENT_EMAIL,
          'i18n' => true,
          'fields' => array(
              'subject' => array(
                  'widget' => array('sfWidgetFormInputText', array('label' => 'Subject'), array('class' => 'span7')),
                  'validator' => array('sfValidatorString', array('max_length' => 120)),
              ),
              'body' => array(
                  'widget' => array('sfWidgetFormTextarea', array('label' => 'Body'), array('class' => 'span7 elastic')),
                  'validator' => array('sfValidatorString', array())
              ),
          )
      ),
      'privacy_agreement_reply' => array(
          'name' => 'Privacy Agreement Email Reply (for all Campaigns) UNUSED',
          'json' => self::PRIVACY_AGREEMENT_REPLY,
          'i18n' => true,
          'fields' => array(
              'subject' => array(
                  'widget' => array('sfWidgetFormInputText', array('label' => 'Subject'), array('class' => 'span7')),
                  'validator' => array('sfValidatorString', array('max_length' => 120)),
              ),
              'body' => array(
                  'widget' => array('sfWidgetFormTextarea', array('label' => 'Body'), array('class' => 'span7 elastic')),
                  'validator' => array('sfValidatorString', array())
              ),
          )
      ),
      'register_mail' => array(
          'name' => 'Register verification mail',
          'json' => self::REGISTER_MAIL,
          'i18n' => true,
          'fields' => array(
              'subject' => array(
                  'widget' => array('sfWidgetFormInputText', array('label' => 'Subject'), array('class' => 'span7')),
                  'validator' => array('sfValidatorString', array('max_length' => 120)),
              ),
              'body' => array(
                  'widget' => array('sfWidgetFormTextarea', array('label' => 'Body'), array('class' => 'span7 elastic highlight')),
                  'validator' => array('ValidatorKeywords', array('keywords' => '#VALIDATION-URL#')),
                  'help' => '#VALIDATION-URL#, #USER-NAME#'
              ),
          )
      ),
      'forgotten_mail' => array(
          'name' => 'Password forgotten mail',
          'json' => self::PASSWORD_FORGOTTEN_MAIL,
          'i18n' => true,
          'fields' => array(
              'subject' => array(
                  'widget' => array('sfWidgetFormInputText', array('label' => 'Subject'), array('class' => 'span7')),
                  'validator' => array('sfValidatorString', array('max_length' => 120)),
              ),
              'body' => array(
                  'widget' => array('sfWidgetFormTextarea', array('label' => 'Body'), array('class' => 'span7 elastic highlight')),
                  'validator' => array('ValidatorKeywords', array('keywords' => '#VALIDATION-URL#')),
                  'help' => '#VALIDATION-URL#, #USER-NAME#'
              ),
          )
      ),
  );

  /**
   * Returns an instance of this class.
   *
   * @return StoreTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('Store');
  }

  /**
   *
   * @param string $key
   * @return Store
   */
  public function findByKey($key) {
    return $this->createQuery('s')->where('s.key = ?', $key)->fetchOne();
  }

  /**
   *
   * @param string $key
   * @return Store
   */
  public function findByKeyCached($key) {
    return $this->createQuery('s')->where('s.key = ?', $key)->useResultCache()->fetchOne();
  }

  /**
   *
   * @param string $key
   * @param string $language_id
   * @return Store
   */
  public function findByKeyAndLanguage($key, $language_id) {
    return $this->createQuery('s')->where('s.key = ? and s.language_id = ?', array($key, $language_id))->fetchOne();
  }

  /**
   *
   * @param string $key
   * @param string $language_id
   * @return Store
   */
  public function findByKeyAndLanguageCached($key, $language_id) {
    return $this->createQuery('s')->where('s.key = ? and s.language_id = ?', array($key, $language_id))->useResultCache()->fetchOne();
  }

  /**
   *
   * @param string $key
   * @param string $language_id
   * @param string $fallback
   * @return Store
   */
  public function findByKeyAndLanguageWithFallback($key, $language_id, $fallback = 'en') {
    $store = $language_id ? $this->findByKeyAndLanguage($key, $language_id) : null;
    if ($store)
      return $store;
    if ($language_id != $fallback)
      return $this->findByKeyAndLanguage($key, $fallback);
    return null;
  }
  
  /**
   *
   * @param string $key
   * @param string $language_id
   * @param string $fallback
   * @return Store
   */
  public function findByKeyAndLanguageWithFallbackCached($key, $language_id, $fallback = 'en') {
    $store = $language_id ? $this->findByKeyAndLanguageCached($key, $language_id) : null;
    if ($store)
      return $store;
    if ($language_id != $fallback)
      return $this->findByKeyAndLanguageCached($key, $fallback);
    return null;
  }

  public function getValueCached($key, $default = null) {
    $store = $this->findByKeyCached($key);
    if ($store)
      return $store->getValue();
    return $default;
  }

  static function value($key, $default = null) {
    return self::getInstance()->getValueCached($key, $default);
  }

  static function version($key, $default = null) {
    $store = self::getInstance()->findByKeyCached($key);

    if ($store)
      return $store->getObjectVersion();
    return $default;
  }

}