<?php

/**
 * TargetListRightsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TargetListRightsTable extends Doctrine_Table {

  /**
   * Returns an instance of this class.
   *
   * @return TargetListRightsTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('TargetListRights');
  }

  /**
   *
   * @param MailingList $mailing_list
   * @param sfGuardUser $user
   * @return Doctrine_Query
   */
  public function queryByTargetListAndUser(MailingList $mailing_list, sfGuardUser $user) {
    return $this->createQuery('tr')
        ->where('tr.mailing_list_id = ? AND tr.user_id = ?', array($mailing_list->getId(), $user->getId()));
  }

  /**
   *
   * @param MailingList $target_list
   * @return Doctrine_Query
   */
  public function queryByTargetList(MailingList $target_list) {
    return $this->createQuery('tr')
        ->where('tr.mailing_list_id = ?', array($target_list->getId()));
  }

  /**
   *
   * @param MailingList $target_list
   * @param type $user_ids
   * @return Doctrine_Query
   */
  public function queryByTargetListAndUsers(MailingList $target_list, $user_ids) {
    return $this->createQuery('tr')
        ->where('tr.mailing_list_id = ?', $target_list->getId())
        ->andWhereIn('tr.user_id', $user_ids);
  }

}