<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('petition', 'email_targets', 'clob', '', array(
             ));
        $this->addColumn('petition_text', 'email_targets', 'clob', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('petition', 'email_targets');
        $this->removeColumn('petition_text', 'email_targets');
    }
}