<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('petition_text', 'privacy_policy_body', 'clob', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('petition_text', 'privacy_policy_body');
    }
}