<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('registry', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'regkey' => 
             array(
              'type' => 'string',
              'unique' => '1',
              'notnull' => '1',
              'length' => '200',
             ),
             'regclass' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'default' => '',
              'length' => '40',
             ),
             'value' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'object_version' => 
             array(
              'notnull' => '',
              'type' => 'string',
              'length' => '15',
             ),
             ), array(
             'indexes' => 
             array(
              'registry_key' => 
              array(
              'fields' => 
              array(
               0 => 'regkey',
              ),
              ),
              'registry_class' => 
              array(
              'fields' => 
              array(
               0 => 'regclass',
              ),
              ),
              'registry_key_class' => 
              array(
              'fields' => 
              array(
               0 => 'regkey',
               1 => 'regclass',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('registry');
    }
}