<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version13 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('mailing_list_meta_choice', 'choice', 'string', '120', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {

    }
}