<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version21 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('petition_signing_wave', 'psw_status', array(
             'fields' => 
             array(
              0 => 'status',
             ),
             ));
        $this->addIndex('petition_signing_wave', 'psw_p_status', array(
             'fields' => 
             array(
              0 => 'petition_signing_id',
              1 => 'status',
             ),
             ));
    }

    public function down()
    {
        $this->removeIndex('petition_signing_wave', 'psw_status', array(
             'fields' => 
             array(
              0 => 'status',
             ),
             ));
        $this->removeIndex('petition_signing_wave', 'psw_p_status', array(
             'fields' => 
             array(
              0 => 'petition_signing_id',
              1 => 'status',
             ),
             ));
    }
}