<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version23 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('petition_signing_wave', 'petition_signing_wave_widget_id_widget_id', array(
             'name' => 'petition_signing_wave_widget_id_widget_id',
             'local' => 'widget_id',
             'foreign' => 'id',
             'foreignTable' => 'widget',
             'onUpdate' => '',
             'onDelete' => 'SET NULL',
             ));
        $this->createForeignKey('petition_signing_wave', 'petition_signing_wave_language_id_language_id', array(
             'name' => 'petition_signing_wave_language_id_language_id',
             'local' => 'language_id',
             'foreign' => 'id',
             'foreignTable' => 'language',
             'onUpdate' => '',
             'onDelete' => 'SET NULL',
             ));
        $this->addIndex('petition_signing_wave', 'petition_signing_wave_widget_id', array(
             'fields' => 
             array(
              0 => 'widget_id',
             ),
             ));
        $this->addIndex('petition_signing_wave', 'petition_signing_wave_language_id', array(
             'fields' => 
             array(
              0 => 'language_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('petition_signing_wave', 'petition_signing_wave_widget_id_widget_id');
        $this->dropForeignKey('petition_signing_wave', 'petition_signing_wave_language_id_language_id');
        $this->removeIndex('petition_signing_wave', 'petition_signing_wave_widget_id', array(
             'fields' => 
             array(
              0 => 'widget_id',
             ),
             ));
        $this->removeIndex('petition_signing_wave', 'petition_signing_wave_language_id', array(
             'fields' => 
             array(
              0 => 'language_id',
             ),
             ));
    }
}