<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version30 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('facebook_tab', 'facebook_tab_widget_id_widget_id', array(
             'name' => 'facebook_tab_widget_id_widget_id',
             'local' => 'widget_id',
             'foreign' => 'id',
             'foreignTable' => 'widget',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('facebook_tab', 'facebook_tab_language_id_language_id', array(
             'name' => 'facebook_tab_language_id_language_id',
             'local' => 'language_id',
             'foreign' => 'id',
             'foreignTable' => 'language',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('facebook_tab', 'facebook_tab_widget_id', array(
             'fields' => 
             array(
              0 => 'widget_id',
             ),
             ));
        $this->addIndex('facebook_tab', 'facebook_tab_language_id', array(
             'fields' => 
             array(
              0 => 'language_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('facebook_tab', 'facebook_tab_widget_id_widget_id');
        $this->dropForeignKey('facebook_tab', 'facebook_tab_language_id_language_id');
        $this->removeIndex('facebook_tab', 'facebook_tab_widget_id', array(
             'fields' => 
             array(
              0 => 'widget_id',
             ),
             ));
        $this->removeIndex('facebook_tab', 'facebook_tab_language_id', array(
             'fields' => 
             array(
              0 => 'language_id',
             ),
             ));
    }
}