<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version34 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('petition_signing', 'subscribe', 'integer', '1', array(
             'notnull' => '1',
             'default' => '0',
             ));
    }

    public function postUp() {
        $conn = Doctrine_Manager::getInstance()->getCurrentConnection();
        $conn->execute('UPDATE petition_signing SET subscribe = 1  WHERE fields LIKE \'%"subscribe":["yes"]%\';');
        $conn->clear();
    }

    public function down()
    {
        $this->removeColumn('petition_signing', 'subscribe');
    }
}