<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version40 extends Doctrine_Migration_Base {

  public function up() {
    
    // fix for mixed collate

    $pdo = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
    foreach (array('campaign', 'contact', 'sf_guard_forgot_password', 'sf_guard_user') as $table) {
      $pdo->query('ALTER TABLE ' . $table . ' CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci');
      $pdo->query('ALTER TABLE ' . $table . ' COLLATE=\'utf8_general_ci\'');
    }
  }

  public function down() {
    
  }

}