<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version41 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('sf_guard_user', 'organisation', 'string', '120', array(
             ));
        $this->addColumn('sf_guard_user', 'website', 'string', '200', array(
             ));
        $this->addColumn('sf_guard_user', 'mobile', 'string', '40', array(
             ));
        $this->addColumn('sf_guard_user', 'phone', 'string', '40', array(
             ));
        $this->addColumn('sf_guard_user', 'street', 'string', '120', array(
             ));
        $this->addColumn('sf_guard_user', 'city', 'string', '120', array(
             ));
        $this->addColumn('sf_guard_user', 'post_code', 'string', '100', array(
             ));
        $this->addColumn('sf_guard_user', 'country', 'string', '2', array(
             ));
        $this->addColumn('sf_guard_user', 'language_id', 'string', '5', array(
             'notnull' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('sf_guard_user', 'organisation');
        $this->removeColumn('sf_guard_user', 'website');
        $this->removeColumn('sf_guard_user', 'mobile');
        $this->removeColumn('sf_guard_user', 'phone');
        $this->removeColumn('sf_guard_user', 'street');
        $this->removeColumn('sf_guard_user', 'city');
        $this->removeColumn('sf_guard_user', 'post_code');
        $this->removeColumn('sf_guard_user', 'country');
        $this->removeColumn('sf_guard_user', 'language_id');
    }
}