<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version38 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('sf_guard_forgot_password', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '4',
             ),
             'unique_key' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'expires_at' => 
             array(
              'type' => 'timestamp',
              'notnull' => '1',
              'length' => '25',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'INNODB',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
        
        $this->renameColumn('sf_guard_user', 'firstname', 'first_name');
        $this->renameColumn('sf_guard_user', 'lastname', 'last_name');
        $this->renameColumn('sf_guard_user', 'email', 'email_address');
        
        $this->changeColumn('sf_guard_remember_key', 'ip_address', 'string', '50', array(
             ));
    }

    public function down()
    {
        $this->dropTable('sf_guard_forgot_password');
        
        $this->renameColumn('sf_guard_user', 'first_name', 'firstname');
        $this->renameColumn('sf_guard_user', 'last_name', 'lastname');
        $this->renameColumn('sf_guard_user', 'email_address', 'email');
    }
}