<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version54 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('ticket', 'ticket_widget_id_widget_id', array(
             'name' => 'ticket_widget_id_widget_id',
             'local' => 'widget_id',
             'foreign' => 'id',
             'foreignTable' => 'widget',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('ticket', 'ticket_widget_id', array(
             'fields' => 
             array(
              0 => 'widget_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('ticket', 'ticket_widget_id_widget_id');
        $this->removeIndex('ticket', 'ticket_widget_id', array(
             'fields' => 
             array(
              0 => 'widget_id',
             ),
             ));
    }
}