<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version58 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('ticket', 'ticket_target_list_id_mailing_list_id', array(
             'name' => 'ticket_target_list_id_mailing_list_id',
             'local' => 'target_list_id',
             'foreign' => 'id',
             'foreignTable' => 'mailing_list',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('ticket', 'ticket_target_list_id', array(
             'fields' => 
             array(
              0 => 'target_list_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('ticket', 'ticket_target_list_id_mailing_list_id');
        $this->removeIndex('ticket', 'ticket_target_list_id', array(
             'fields' => 
             array(
              0 => 'target_list_id',
             ),
             ));
    }
}