<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version61 extends Doctrine_Migration_Base {

  public function up() {
    $this->changeColumn('store', 'key_', 'string', '80', array(
        'notnull' => '1',
        'unique' => '',
        'alias' => 'key',
    ));

    $pdo = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
    $pdo->query("ALTER TABLE `store` DROP INDEX `key_`, ADD INDEX `key_` (`key_`)");
    
  }

  public function down() {
    
  }

}