<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version66 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('mailing_list', 'campaign_id', 'integer', '4', array(
             'notnull' => '',
             ));
    }

    public function down()
    {

    }
}