<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version73 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('mailing_list_meta_choice', 'mlmc_ml_choice', array(
             'fields' => 
             array(
              0 => 'mailing_list_meta_id',
              1 => 'choice',
             ),
             ));
    }

    public function down()
    {
        $this->removeIndex('mailing_list_meta_choice', 'mlmc_ml_choice', array(
             'fields' => 
             array(
              0 => 'mailing_list_meta_id',
              1 => 'choice',
             ),
             ));
    }
}