<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version74 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('petition', 'with_comments', 'integer', '1', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('petition', 'with_address', 'integer', '1', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('petition', 'with_country', 'integer', '1', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('petition', 'default_country', 'string', '5', array(
             'notnull' => '1',
             'default' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('petition', 'with_comments');
        $this->removeColumn('petition', 'with_address');
        $this->removeColumn('petition', 'with_country');
        $this->removeColumn('petition', 'default_country');
    }
}