<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version80 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('petition_contact', array(
             'petition_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '4',
             ),
             'contact_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '4',
             ),
             'secret' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '40',
             ),
             'password' => 
             array(
              'type' => 'string',
              'notnull' => '',
              'length' => '255',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'petition_id',
              1 => 'contact_id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('pledge_item', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'petition_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '4',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '80',
             ),
             'icon' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'default' => 'star',
              'length' => '80',
             ),
             'color' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'default' => '000000',
              'length' => '6',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('pledge_text', array(
             'pledge_item_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '4',
             ),
             'petition_text_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '4',
             ),
             'text' => 
             array(
              'type' => 'clob',
              'notnull' => '1',
              'default' => '',
              'length' => '',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'pledge_item_id',
              1 => 'petition_text_id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('plegde', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'pledge_item_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '4',
             ),
             'contact_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '4',
             ),
             'status' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'default' => '0',
              'length' => '1',
             ),
             'comment' => 
             array(
              'type' => 'clob',
              'notnull' => '',
              'length' => '',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('petition_contact');
        $this->dropTable('pledge_item');
        $this->dropTable('pledge_text');
        $this->dropTable('plegde');
    }
}