<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version93 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('petition_text', 'pledge_thank_you', 'clob', '', array(
             'notnull' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('petition_text', 'pledge_thank_you');
    }
}