<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version109 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('petition_signing', 'signing_petition_count_index3', array(
             'fields' => 
             array(
              0 => 'petition_id',
              1 => 'status',
              2 => 'country',
              3 => 'created_at',
             ),
             ));
    }

    public function down()
    {
        $this->removeIndex('petition_signing', 'signing_petition_count_index3', array(
             'fields' => 
             array(
              0 => 'petition_id',
              1 => 'status',
              2 => 'country',
              3 => 'created_at',
             ),
             ));
    }
}