<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version119 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('download', 'subscriber', 'integer', '1', array(
             'notnull' => '1',
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->removeColumn('download', 'subscriber');
    }
}