<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version122 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('quota', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'status' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'default' => '1',
              'length' => '4',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'unique' => '1',
              'length' => '120',
             ),
             'price' => 
             array(
              'type' => 'decimal',
              'notnull' => '1',
              'scale' => '2',
              'length' => '10',
             ),
             'days' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '4',
             ),
             'emails' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '4',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'notnull' => '',
              'length' => '4',
             ),
             'campaign_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '4',
             ),
             'start_at' => 
             array(
              'type' => 'date',
              'notnull' => '',
              'length' => '25',
             ),
             'end_at' => 
             array(
              'type' => 'date',
              'notnull' => '',
              'length' => '25',
             ),
             'paid_at' => 
             array(
              'type' => 'date',
              'notnull' => '',
              'length' => '25',
             ),
             'emails_remaining' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'default' => '0',
              'length' => '4',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('quota');
    }
}