<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version140 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('offer', 'offer_user_id_sf_guard_user_id', array(
             'name' => 'offer_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'SET NULL',
             ));
        $this->createForeignKey('offer', 'offer_campaign_id_campaign_id', array(
             'name' => 'offer_campaign_id_campaign_id',
             'local' => 'campaign_id',
             'foreign' => 'id',
             'foreignTable' => 'campaign',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('offer_item', 'offer_item_offer_id_offer_id', array(
             'name' => 'offer_item_offer_id_offer_id',
             'local' => 'offer_id',
             'foreign' => 'id',
             'foreignTable' => 'offer',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('offer', 'offer_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('offer', 'offer_campaign_id', array(
             'fields' => 
             array(
              0 => 'campaign_id',
             ),
             ));
        $this->addIndex('offer_item', 'offer_item_offer_id', array(
             'fields' => 
             array(
              0 => 'offer_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('offer', 'offer_user_id_sf_guard_user_id');
        $this->dropForeignKey('offer', 'offer_campaign_id_campaign_id');
        $this->dropForeignKey('offer_item', 'offer_item_offer_id_offer_id');
        $this->removeIndex('offer', 'offer_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('offer', 'offer_campaign_id', array(
             'fields' => 
             array(
              0 => 'campaign_id',
             ),
             ));
        $this->removeIndex('offer_item', 'offer_item_offer_id', array(
             'fields' => 
             array(
              0 => 'offer_id',
             ),
             ));
    }
}