<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version141 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('campaign', 'public_enabled', 'integer', '1', array(
             'notnull' => '1',
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->removeColumn('campaign', 'public_enabled');
    }
}