<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version147 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('petition', 'donate_url', 'string', '200', array(
             'notnull' => '',
             ));
        $this->addColumn('petition_text', 'donate_url', 'string', '200', array(
             'notnull' => '',
             ));
        $this->addColumn('petition_text', 'donate_text', 'clob', '', array(
             'notnull' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('petition', 'donate_url');
        $this->removeColumn('petition_text', 'donate_url');
        $this->removeColumn('petition_text', 'donate_text');
    }
}