<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version154 extends Doctrine_Migration_Base {

  public function up() {
    $this->addColumn('petition', 'validation_required', 'integer', '4', array(
        'notnull' => '1',
        'default' => '1',
    ));
    $this->addColumn('petition_signing', 'verified', 'integer', '4', array(
        'notnull' => '1',
        'default' => '0',
    ));
  }

  public function postUp() {
    $conn = Doctrine_Manager::getInstance()->getCurrentConnection();
    $conn->execute('UPDATE petition_signing SET verified = ? WHERE status = ?', array(PetitionSigning::VERIFIED_YES, PetitionSigning::STATUS_COUNTED));
    $conn->clear();
  }

  public function preDown() {
    $conn = Doctrine_Manager::getInstance()->getCurrentConnection();
    $conn->execute('UPDATE petition_signing SET status = ? WHERE verified = ? AND status = ?', array(PetitionSigning::STATUS_PENDING, PetitionSigning::VERIFIED_NO, PetitionSigning::STATUS_COUNTED));
    $conn->clear();
  }

  public function down() {
    $this->removeColumn('petition', 'validation_required');
    $this->removeColumn('petition_signing', 'verified');
  }

}
