<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version153 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('widget', 'widget_email', array(
             'fields' => 
             array(
              0 => 'email',
              1 => 'user_id',
             ),
             ));
    }

    public function down()
    {
        $this->removeIndex('widget', 'widget_email', array(
             'fields' => 
             array(
              0 => 'email',
              1 => 'user_id',
             ),
             ));
    }
}