<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version158 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('country_tax', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'country' => 
             array(
              'type' => 'string',
              'unique' => '1',
              'notnull' => '1',
              'length' => '2',
             ),
             'tax_no_vat' => 
             array(
              'type' => 'decimal',
              'notnull' => '1',
              'scale' => '2',
              'length' => '5',
             ),
             'no_vat_note_id' => 
             array(
              'type' => 'integer',
              'notnull' => '',
              'length' => '4',
             ),
             'tax_vat' => 
             array(
              'type' => 'decimal',
              'notnull' => '1',
              'scale' => '2',
              'length' => '5',
             ),
             'vat_note_id' => 
             array(
              'type' => 'integer',
              'notnull' => '',
              'length' => '4',
             ),
             ), array(
             'type' => 'INNODB',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('tax_note', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'name' => 
             array(
              'type' => 'string',
              'unique' => '1',
              'length' => '40',
             ),
             'note' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             ), array(
             'type' => 'INNODB',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('country_tax');
        $this->dropTable('tax_note');
    }
}