<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version161 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('bill', 'tax_note', 'clob', '', array(
             ));
        $this->addColumn('offer', 'tax_note', 'clob', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('bill', 'tax_note');
        $this->removeColumn('offer', 'tax_note');
    }
}