<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version166 extends Doctrine_Migration_Base {

  public function up() {
    $this->addColumn('petition', 'style_button_primary_color', 'string', '7', array(
        'notnull' => '1',
        'default' => '#76b235',
    ));
    $this->addColumn('petition', 'style_label_color', 'string', '7', array(
        'notnull' => '1',
        'default' => '#666666',
    ));
  }

  public function down() {
    $this->removeColumn('petition', 'style_button_primary_color');
    $this->removeColumn('petition', 'style_label_color');
  }

  public function postUp() {
    parent::postUp();

    $q = Doctrine_Manager::getInstance()->getCurrentConnection();
    $q->exec('UPDATE petition SET style_button_primary_color = style_button_color, style_label_color = style_body_color');
  }

}
