<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version167 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('petition_text', 'title', 'string', '', array(
             'notnull' => '',
             'default' => '',
             ));
        $this->changeColumn('widget', 'title', 'string', '', array(
             'notnull' => '',
             'default' => '',
             ));
    }

    public function down()
    {

    }
}