<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version171 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('petition_signing', 'signing_last_signers', array(
             'fields' => 
             array(
              0 => 'petition_id',
              1 => 'status',
              2 => 'updated_at',
             ),
             ));
    }

    public function down()
    {
        $this->removeIndex('petition_signing', 'signing_last_signers', array(
             'fields' => 
             array(
              0 => 'petition_id',
              1 => 'status',
              2 => 'updated_at',
             ),
             ));
    }
}