<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version174 extends Doctrine_Migration_Base {

  public function up() {
    $this->addColumn('petition', 'titletype', 'integer', '1', array(
        'notnull' => '1',
        'default' => '0',
    ));
  }

  public function postUp() {
    $conn = Doctrine_Manager::getInstance()->getCurrentConnection();
    $conn->execute('UPDATE petition SET titletype = 2 WHERE nametype = 1;');
    $conn->clear();
  }

  public function down() {
    $this->removeColumn('petition', 'titletype');
  }

}
