<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version186 extends Doctrine_Migration_Base {

  public function up() {
    $this->dropForeignKey('download', 'download_user_id_sf_guard_user_id');
    $this->createForeignKey('download', 'download_user_id_sf_guard_user_id', array(
        'name' => 'download_user_id_sf_guard_user_id',
        'local' => 'user_id',
        'foreign' => 'id',
        'foreignTable' => 'sf_guard_user',
        'onUpdate' => '',
        'onDelete' => 'SET NULL',
    ));
  }

  public function down() {
    $this->dropForeignKey('download', 'download_user_id_sf_guard_user_id');
    $this->createForeignKey('download', 'download_user_id_sf_guard_user_id', array(
        'name' => 'download_user_id_sf_guard_user_id',
        'local' => 'user_id',
        'foreign' => 'id',
        'foreignTable' => 'sf_guard_user',
        'onUpdate' => '',
        'onDelete' => 'CASCADE',
    ));
  }

}
