<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version183 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('contact', 'bounce', 'integer', '1', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('contact', 'bounce_at', 'timestamp', '25', array(
             'notnull' => '',
             ));
        $this->addColumn('contact', 'bounce_blocked', 'integer', '1', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('contact', 'bounce_hard', 'integer', '1', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('contact', 'bounce_related_to', 'string', '20', array(
             'notnull' => '',
             ));
        $this->addColumn('contact', 'bounce_error', 'string', '20', array(
             'notnull' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('contact', 'bounce');
        $this->removeColumn('contact', 'bounce_at');
        $this->removeColumn('contact', 'bounce_blocked');
        $this->removeColumn('contact', 'bounce_hard');
        $this->removeColumn('contact', 'bounce_related_to');
        $this->removeColumn('contact', 'bounce_error');
    }
}