<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version195 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('petition', 'email_button_color', 'string', '7', array(
             'notnull' => '1',
             'default' => '#b7d9f9',
             ));
    }

    public function down()
    {
        $this->removeColumn('petition', 'email_button_color');
    }
}