<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version197 extends Doctrine_Migration_Base {

  public function up() {
    $conn = Doctrine_Manager::getInstance()->getCurrentConnection();
    $conn->execute("UPDATE petition_text SET email_validation_body = REPLACE(email_validation_body,'#VALIDATION-URL#', '[Email Validation](#VALIDATION-URL#)')");
    $conn->clear();
  }

  public function down() {
    $conn = Doctrine_Manager::getInstance()->getCurrentConnection();
    $conn->execute("UPDATE petition_text SET email_validation_body = REPLACE(email_validation_body,'[#VALIDATION-URL#](Email Validation)', '#VALIDATION-URL#')");
    $conn->clear();
  }

}
