<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version199 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('widget', 'email_targets', 'clob', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('widget', 'email_targets');
    }
}