<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version203 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('invitation_campaign', 'invitation_campaign_invited_by_id_sf_guard_user_id', array(
             'name' => 'invitation_campaign_invited_by_id_sf_guard_user_id',
             'local' => 'invited_by_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('invitation_campaign', 'invitation_campaign_invited_by_id', array(
             'fields' => 
             array(
              0 => 'invited_by_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('invitation_campaign', 'invitation_campaign_invited_by_id_sf_guard_user_id');
        $this->removeIndex('invitation_campaign', 'invitation_campaign_invited_by_id', array(
             'fields' => 
             array(
              0 => 'invited_by_id',
             ),
             ));
    }
}