<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version200 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('invitation', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'email_address' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'unique' => '1',
              'length' => '80',
             ),
             'validation_code' => 
             array(
              'type' => 'string',
              'length' => '20',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'INNODB',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('invitation_campaign', array(
             'invitation_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '4',
             ),
             'campaign_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '4',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'INNODB',
             'primary' => 
             array(
              0 => 'invitation_id',
              1 => 'campaign_id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('invitation');
        $this->dropTable('invitation_campaign');
    }
}