<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version205 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('invitation', 'invitation_register_user_id_sf_guard_user_id', array(
             'name' => 'invitation_register_user_id_sf_guard_user_id',
             'local' => 'register_user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('invitation', 'invitation_register_user_id', array(
             'fields' => 
             array(
              0 => 'register_user_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('invitation', 'invitation_register_user_id_sf_guard_user_id');
        $this->removeIndex('invitation', 'invitation_register_user_id', array(
             'fields' => 
             array(
              0 => 'register_user_id',
             ),
             ));
    }
}