<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version204 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('invitation', 'register_user_id', 'integer', '4', array(
             'notnull' => '',
             ));
        $this->changeColumn('invitation', 'validation_code', 'string', '40', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('invitation', 'register_user_id');
    }
}