<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version207 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('petition', 'keywords_subst', 'string', '250', array(
             'notnull' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('petition', 'keywords_subst');
    }
}