<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version213 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('product', 'subscription', 'integer', '1', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('quota', 'subscription', 'integer', '1', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('quota', 'renew_offerred', 'integer', '1', array(
             'notnull' => '1',
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->removeColumn('product', 'subscription');
        $this->removeColumn('quota', 'subscription');
        $this->removeColumn('quota', 'renew_offerred');
    }
}