<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version217 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('digest_email', 'digest_email_petition_id_petition_id', array(
             'name' => 'digest_email_petition_id_petition_id',
             'local' => 'petition_id',
             'foreign' => 'id',
             'foreignTable' => 'petition',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('digest_email', 'digest_email_contact_id_contact_id', array(
             'name' => 'digest_email_contact_id_contact_id',
             'local' => 'contact_id',
             'foreign' => 'id',
             'foreignTable' => 'contact',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('digest_email', 'digest_email_petition_signing_id_petition_signing_id', array(
             'name' => 'digest_email_petition_signing_id_petition_signing_id',
             'local' => 'petition_signing_id',
             'foreign' => 'id',
             'foreignTable' => 'petition_signing',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('digest_email', 'digest_email_petition_id', array(
             'fields' => 
             array(
              0 => 'petition_id',
             ),
             ));
        $this->addIndex('digest_email', 'digest_email_contact_id', array(
             'fields' => 
             array(
              0 => 'contact_id',
             ),
             ));
        $this->addIndex('digest_email', 'digest_email_petition_signing_id', array(
             'fields' => 
             array(
              0 => 'petition_signing_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('digest_email', 'digest_email_petition_id_petition_id');
        $this->dropForeignKey('digest_email', 'digest_email_contact_id_contact_id');
        $this->dropForeignKey('digest_email', 'digest_email_petition_signing_id_petition_signing_id');
        $this->removeIndex('digest_email', 'digest_email_petition_id', array(
             'fields' => 
             array(
              0 => 'petition_id',
             ),
             ));
        $this->removeIndex('digest_email', 'digest_email_contact_id', array(
             'fields' => 
             array(
              0 => 'contact_id',
             ),
             ));
        $this->removeIndex('digest_email', 'digest_email_petition_signing_id', array(
             'fields' => 
             array(
              0 => 'petition_signing_id',
             ),
             ));
    }
}