<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version223 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('petition_signing', 'petition_signing_campaign_id_campaign_id', array(
             'name' => 'petition_signing_campaign_id_campaign_id',
             'local' => 'campaign_id',
             'foreign' => 'id',
             'foreignTable' => 'campaign',
             ));
        $this->createForeignKey('petition_signing', 'petition_signing_petition_text_id_petition_text_id', array(
             'name' => 'petition_signing_petition_text_id_petition_text_id',
             'local' => 'petition_text_id',
             'foreign' => 'id',
             'foreignTable' => 'petition_text',
             ));
        $this->createForeignKey('petition_signing', 'petition_signing_language_id_language_id', array(
             'name' => 'petition_signing_language_id_language_id',
             'local' => 'language_id',
             'foreign' => 'id',
             'foreignTable' => 'language',
             ));
        $this->addIndex('petition_signing', 'petition_signing_campaign_id', array(
             'fields' => 
             array(
              0 => 'campaign_id',
             ),
             ));
        $this->addIndex('petition_signing', 'petition_signing_petition_text_id', array(
             'fields' => 
             array(
              0 => 'petition_text_id',
             ),
             ));
        $this->addIndex('petition_signing', 'petition_signing_language_id', array(
             'fields' => 
             array(
              0 => 'language_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('petition_signing', 'petition_signing_campaign_id_campaign_id');
        $this->dropForeignKey('petition_signing', 'petition_signing_petition_text_id_petition_text_id');
        $this->dropForeignKey('petition_signing', 'petition_signing_language_id_language_id');
        $this->removeIndex('petition_signing', 'petition_signing_campaign_id', array(
             'fields' => 
             array(
              0 => 'campaign_id',
             ),
             ));
        $this->removeIndex('petition_signing', 'petition_signing_petition_text_id', array(
             'fields' => 
             array(
              0 => 'petition_text_id',
             ),
             ));
        $this->removeIndex('petition_signing', 'petition_signing_language_id', array(
             'fields' => 
             array(
              0 => 'language_id',
             ),
             ));
    }
}