<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version222 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('petition_signing', 'campaign_id', 'integer', '4', array(
             'notnull' => '',
             ));
        $this->addColumn('petition_signing', 'petition_text_id', 'integer', '4', array(
             'notnull' => '',
             ));
        $this->addColumn('petition_signing', 'language_id', 'string', '5', array(
             'notnull' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('petition_signing', 'campaign_id');
        $this->removeColumn('petition_signing', 'petition_text_id');
        $this->removeColumn('petition_signing', 'language_id');
    }
}
