<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version227 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('petition_signing', 'signing_language3', array(
             'fields' => 
             array(
              0 => 'campaign_id',
              1 => 'petition_enabled',
              2 => 'status',
              3 => 'language_id',
              4 => 'id',
             ),
             ));
        $this->addIndex('petition_signing', 'signing_list_campaign', array(
             'fields' => 
             array(
              0 => 'campaign_id',
              1 => 'petition_enabled',
              2 => 'status',
              3 => 'id',
             ),
             ));
        $this->addIndex('petition_signing', 'signing_campaign_country', array(
             'fields' => 
             array(
              0 => 'campaign_id',
              1 => 'petition_enabled',
              2 => 'status',
              3 => 'country',
             ),
             ));
    }

    public function down()
    {
        $this->removeIndex('petition_signing', 'signing_language3', array(
             'fields' => 
             array(
              0 => 'campaign_id',
              1 => 'petition_enabled',
              2 => 'status',
              3 => 'language_id',
              4 => 'id',
             ),
             ));
        $this->removeIndex('petition_signing', 'signing_list_campaign', array(
             'fields' => 
             array(
              0 => 'campaign_id',
              1 => 'petition_enabled',
              2 => 'status',
              3 => 'id',
             ),
             ));
        $this->removeIndex('petition_signing', 'signing_campaign_country', array(
             'fields' => 
             array(
              0 => 'campaign_id',
              1 => 'petition_enabled',
              2 => 'status',
              3 => 'country',
             ),
             ));
    }
}