<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version232 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('petition_signing', 'ref_shown', 'integer', '1', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('petition_signing', 'ref_hash', 'string', '80', array(
             'notnull' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('petition_signing', 'ref_shown');
        $this->removeColumn('petition_signing', 'ref_hash');
    }
}