<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version231 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('widget', 'default_country', 'string', '5', array(
             'notnull' => '1',
             'default' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('widget', 'default_country');
    }
}