<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version241 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('widget', 'subscribe_default', 'integer', '1', array(
             'notnull' => '1',
             'default' => '-1',
             ));
        $this->addColumn('widget', 'subscribe_text', 'string', '250', array(
             'notnull' => '',
             'default' => '',
             ));
    }

    public function down()
    {
        $this->removeColumn('widget', 'subscribe_default');
        $this->removeColumn('widget', 'subscribe_text');
    }
}