<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version245 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('petition', 'privacy_policy_by_widget_data_owner', 'integer', '1', array(
             'notnull' => '1',
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->removeColumn('petition', 'privacy_policy_by_widget_data_owner');
    }
}